modelManagement: ModelManager Class Reference
ModelManager Class Reference
Resumen corto aca.
Inherited by EastModelManager, and SimulinkModelManager.
Public Member Functions
ModelManager ()
Brief desc ends here.
ModelManager (String modelPath)
ModelManager (URI model)
void loadIt () throws InvalidModelException
void saveIt () throws IOException
void saveAs (String pathname) throws IOException
void saveAs (URI modelURI) throws IOException
void saveAsWithPropperExtension (String originalPathName) throws IOException
String replaceExtension (String pathName, String extension)
void validateIt () throws InvalidModelException
EObject getTopElement ()
void setTopElement (EObject topElement)
String getNsURI ()
EFactory getFactory ()
String getFileExtension ()
Protected Member Functions
abstract void initMetaModel ()
void init (URI model)
void setFileExtension (String fileExtension)
Protected Attributes
URI model
Resource resource
ResourceSet resourceSet = new ResourceSetImpl()
EPackage ePackage = null
String fileExtension = Resource.Factory.Registry.DEFAULT_EXTENSION
Private Member Functions
void setTopElementIn (Resource aResource)
void setTopElementIn (EObject topElement, Resource aResource)
Resource createNewResource (URI modelURI)
void setResourceFactoryForFileExtension (String extension)
Register the appropriate resource factory to handle file extensions.
Detailed Description
Resumen corto aca.
This class can read from file, validate, and write to file ecore models. It can be used in Java standalone mode, as it first registers the metamodel. In order to write models, subclasses should define initMetaModel method.
Author:
Alex Schenkman
Definition at line 28 of file ModelManager.java.
Constructor & Destructor Documentation
ModelManager ()
Brief desc ends here.
The rest is the detailed description. or Am i wrong?
Definition at line 43 of file ModelManager.java.
ModelManager (String modelPath)
Parameters:
modelPath File path to a model file.
Definition at line 50 of file ModelManager.java.
ModelManager (URI model)
Definition at line 54 of file ModelManager.java.
References ModelManager.init().
Member Function Documentation
Resource createNewResource (URI modelURI) [private]
Definition at line 118 of file ModelManager.java.
References ModelManager.resourceSet.
Referenced by ModelManager.saveAs(), and ModelManager.setTopElement().
EFactory getFactory ()
Reimplemented in EastModelManager, and SimulinkModelManager.
Definition at line 126 of file ModelManager.java.
References ModelManager.ePackage.
String getFileExtension ()
Definition at line 147 of file ModelManager.java.
References ModelManager.fileExtension.
String getNsURI ()
Definition at line 122 of file ModelManager.java.
References ModelManager.ePackage.
EObject getTopElement ()
Definition at line 105 of file ModelManager.java.
References ModelManager.resource.
Referenced by ModelManager.saveIt(), ModelManager.setTopElementIn(), and SimulinkModelManagerTest.testNewModel().
void init (URI model) [protected]
Definition at line 141 of file ModelManager.java.
References ModelManager.fileExtension, ModelManager.initMetaModel(), and ModelManager.setResourceFactoryForFileExtension().
Referenced by EastModelManager.EastModelManager(), ModelManager.ModelManager(), and SimulinkModelManager.SimulinkModelManager().
abstract void initMetaModel () [protected, pure virtual]
Implemented in EastModelManager, and SimulinkModelManager.
Referenced by ModelManager.init().
void loadIt () throws InvalidModelException
Definition at line 58 of file ModelManager.java.
References ModelManager.model, ModelManager.resource, and ModelManager.resourceSet.
Referenced by SimulinkModelManagerTest.testNewModel(), and EastModelManagerTest.testValid().
String replaceExtension (String pathName, String extension)
Definition at line 87 of file ModelManager.java.
Referenced by ModelManager.saveAsWithPropperExtension(), and SimulinkModelManagerTest.testReplacExtension().
void saveAs (URI modelURI) throws IOException
Definition at line 75 of file ModelManager.java.
References ModelManager.createNewResource(), and ModelManager.setTopElementIn().
void saveAs (String pathname) throws IOException
Definition at line 70 of file ModelManager.java.
Referenced by ModelManager.saveAsWithPropperExtension(), and ModelManager.saveIt().
void saveAsWithPropperExtension (String originalPathName) throws IOException
Definition at line 81 of file ModelManager.java.
References ModelManager.fileExtension, ModelManager.replaceExtension(), and ModelManager.saveAs().
void saveIt () throws IOException
Definition at line 62 of file ModelManager.java.
References ModelManager.getTopElement(), ModelManager.model, ModelManager.resource, and ModelManager.saveAs().
Referenced by SimulinkModelManagerTest.testNewModel().
void setFileExtension (String fileExtension) [protected]
Definition at line 151 of file ModelManager.java.
Referenced by EastModelManager.EastModelManager(), and SimulinkModelManager.SimulinkModelManager().
void setResourceFactoryForFileExtension (String extension) [private]
Register the appropriate resource factory to handle file extensions.
In this case, all files (*) will handled by XMI resource Factory.
Definition at line 134 of file ModelManager.java.
References ModelManager.resourceSet.
Referenced by ModelManager.init().
void setTopElement (EObject topElement)
Definition at line 111 of file ModelManager.java.
References ModelManager.createNewResource(), ModelManager.model, ModelManager.resource, and ModelManager.setTopElementIn().
Referenced by SimulinkModelManagerTest.testNewModel().
void setTopElementIn (EObject topElement, Resource aResource) [private]
Definition at line 95 of file ModelManager.java.
void setTopElementIn (Resource aResource) [private]
Definition at line 91 of file ModelManager.java.
References ModelManager.getTopElement().
Referenced by ModelManager.saveAs(), and ModelManager.setTopElement().
void validateIt () throws InvalidModelException
Definition at line 99 of file ModelManager.java.
References ModelValidator.doIt(), and ModelManager.resource.
Referenced by EastModelManagerTest.testValid().
Member Data Documentation
EPackage ePackage = null [protected]
Definition at line 33 of file ModelManager.java.
Referenced by ModelManager.getFactory(), ModelManager.getNsURI(), SimulinkModelManager.initMetaModel(), and EastModelManager.initMetaModel().
String fileExtension = Resource.Factory.Registry.DEFAULT_EXTENSION [protected]
Definition at line 34 of file ModelManager.java.
Referenced by ModelManager.getFileExtension(), ModelManager.init(), and ModelManager.saveAsWithPropperExtension().
URI model [protected]
Definition at line 30 of file ModelManager.java.
Referenced by ModelManager.loadIt(), ModelManager.saveIt(), and ModelManager.setTopElement().
Resource resource [protected]
Definition at line 31 of file ModelManager.java.
Referenced by ModelManager.getTopElement(), ModelManager.loadIt(), ModelManager.saveIt(), ModelManager.setTopElement(), and ModelManager.validateIt().
ResourceSet resourceSet = new ResourceSetImpl() [protected]
Definition at line 32 of file ModelManager.java.
Referenced by ModelManager.createNewResource(), ModelManager.loadIt(), and ModelManager.setResourceFactoryForFileExtension().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelManagement/ModelManager.java