modelManagement: SimulinkModelManagerTest Class Reference
SimulinkModelManagerTest Class Reference
Public Member Functions
SimulinkModelManager testInstanceCreation () throws InvalidURIException
SimulinkModelManager testReplacExtension (SimulinkModelManager aModelMgr)
SimulinkModelManager testExtension (SimulinkModelManager aModelMgr)
SimulinkModelManager testMetaModelRegistration (SimulinkModelManager aModelMgr)
SimulinkModelManager testLoadIt (SimulinkModelManager aModelMgr) throws InvalidModelException
EObject testGetTopElement (SimulinkModelManager aModelMgr)
void testNewModel ()
Private Attributes
String modelPath = "testWorkspace/demo.simulink"
URI model = URI.createFileURI(modelPath)
Detailed Description
Definition at line 27 of file SimulinkModelManagerTest.java.
Member Function Documentation
SimulinkModelManager testExtension (SimulinkModelManager aModelMgr)
Definition at line 50 of file SimulinkModelManagerTest.java.
EObject testGetTopElement (SimulinkModelManager aModelMgr)
Definition at line 88 of file SimulinkModelManagerTest.java.
SimulinkModelManager testInstanceCreation () throws InvalidURIException
Definition at line 33 of file SimulinkModelManagerTest.java.
SimulinkModelManager testLoadIt (SimulinkModelManager aModelMgr) throws InvalidModelException
Definition at line 73 of file SimulinkModelManagerTest.java.
References InvalidModelException.dumpInvalidObjectsToConsole().
SimulinkModelManager testMetaModelRegistration (SimulinkModelManager aModelMgr)
Definition at line 57 of file SimulinkModelManagerTest.java.
void testNewModel ()
Definition at line 97 of file SimulinkModelManagerTest.java.
References SimulinkModelManager.getFactory(), ModelManager.getTopElement(), ModelManager.loadIt(), ModelManager.saveIt(), and ModelManager.setTopElement().
SimulinkModelManager testReplacExtension (SimulinkModelManager aModelMgr)
Definition at line 42 of file SimulinkModelManagerTest.java.
References ModelManager.replaceExtension().
Member Data Documentation
URI model = URI.createFileURI(modelPath) [private]
Definition at line 30 of file SimulinkModelManagerTest.java.
String modelPath = "testWorkspace/demo.simulink" [private]
Definition at line 29 of file SimulinkModelManagerTest.java.
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelManagement/simulink/SimulinkModelManagerTest.java