modelManagement: ModelValidator Class Reference
ModelValidator Class Reference
Public Member Functions
ModelValidator (Resource resource)
void doIt () throws InvalidModelException
Package Attributes
Resource resource
Hashtable< EObject, String > invalidObjects
StringBuffer strBuffer
Private Member Functions
void validateEachElement ()
void addToListIfInvalid (EObject eObject)
Boolean validateEObject (EObject eObject)
void resetStringBuffer ()
void printDiagnostic (Diagnostic diagnostic, String indent)
void recordIndentedMessage (String message, String indent)
Detailed Description
Definition at line 14 of file ModelValidator.java.
Constructor & Destructor Documentation
ModelValidator (Resource resource)
Definition at line 20 of file ModelValidator.java.
References ModelValidator.invalidObjects.
Member Function Documentation
void addToListIfInvalid (EObject eObject) [private]
Definition at line 42 of file ModelValidator.java.
References ModelValidator.invalidObjects, ModelValidator.strBuffer, and ModelValidator.validateEObject().
Referenced by ModelValidator.validateEachElement().
void doIt () throws InvalidModelException
Definition at line 25 of file ModelValidator.java.
References ModelValidator.invalidObjects, and ModelValidator.validateEachElement().
Referenced by ModelManager.validateIt().
void printDiagnostic (Diagnostic diagnostic, String indent) [private]
Definition at line 63 of file ModelValidator.java.
References ModelValidator.recordIndentedMessage().
Referenced by ModelValidator.validateEObject().
void recordIndentedMessage (String message, String indent) [private]
Parameters:
message
indent
Definition at line 75 of file ModelValidator.java.
References ModelValidator.strBuffer.
Referenced by ModelValidator.printDiagnostic().
void resetStringBuffer () [private]
Definition at line 58 of file ModelValidator.java.
References ModelValidator.strBuffer.
Referenced by ModelValidator.validateEObject().
void validateEachElement () [private]
Definition at line 36 of file ModelValidator.java.
References ModelValidator.addToListIfInvalid(), and ModelValidator.resource.
Referenced by ModelValidator.doIt().
Boolean validateEObject (EObject eObject) [private]
Definition at line 48 of file ModelValidator.java.
References ModelValidator.printDiagnostic(), and ModelValidator.resetStringBuffer().
Referenced by ModelValidator.addToListIfInvalid().
Member Data Documentation
Hashtable<EObject, String> invalidObjects [package]
Definition at line 17 of file ModelValidator.java.
Referenced by ModelValidator.addToListIfInvalid(), ModelValidator.doIt(), and ModelValidator.ModelValidator().
Resource resource [package]
Definition at line 16 of file ModelValidator.java.
Referenced by ModelValidator.validateEachElement().
StringBuffer strBuffer [package]
Definition at line 18 of file ModelValidator.java.
Referenced by ModelValidator.addToListIfInvalid(), ModelValidator.recordIndentedMessage(), and ModelValidator.resetStringBuffer().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelManagement/ModelValidator.java