modelManagement: EastModelManagerTest Class Reference
EastModelManagerTest Class Reference
Public Member Functions
void testValid () throws InvalidModelException
Static Public Member Functions
static void main (String[] args) throws InvalidModelException
Private Attributes
String modelPath = "../ATLtrafos/testFiles/MyEASTModel1.uml"
URI modelURI = URI.createFileURI(modelPath)
Detailed Description
Definition at line 11 of file EastModelManagerTest.java.
Member Function Documentation
static void main (String[] args) throws InvalidModelException [static]
Definition at line 23 of file EastModelManagerTest.java.
References EastModelManagerTest.testValid().
void testValid () throws InvalidModelException
Definition at line 16 of file EastModelManagerTest.java.
References ModelManager.loadIt(), EastModelManagerTest.modelURI, and ModelManager.validateIt().
Referenced by EastModelManagerTest.main().
Member Data Documentation
String modelPath = "../ATLtrafos/testFiles/MyEASTModel1.uml" [private]
Definition at line 13 of file EastModelManagerTest.java.
URI modelURI = URI.createFileURI(modelPath) [private]
Definition at line 14 of file EastModelManagerTest.java.
Referenced by EastModelManagerTest.testValid().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelManagement/east/EastModelManagerTest.java