modelManagement: SimulinkModelManager Class Reference
SimulinkModelManager Class Reference
A ModelManager that can handle simulink-ecore models.
Inherits se::kth::md::simulinkExchange::modelManagement::ModelManager.
Public Member Functions
SimulinkFactory getFactory ()
SimulinkModelManager ()
Opens an empty simulink-ecore model named: "unnamed.simulink".
SimulinkModelManager (String modelPath)
Opens a simulink-ecore model from file.
SimulinkModelManager (URI model)
Opens a simulink-ecore model from the given model.
void testReplacExtension ()
Protected Member Functions
void initMetaModel ()
Adds the metamodel the the global EMF registry and initializes the metamodel factory.
Detailed Description
A ModelManager that can handle simulink-ecore models.
Author:
Alex Schenkman
Definition at line 18 of file SimulinkModelManager.java.
Constructor & Destructor Documentation
SimulinkModelManager ()
Opens an empty simulink-ecore model named: "unnamed.simulink".
Relies on SimulinkModelManager(String modelPath).
Definition at line 39 of file SimulinkModelManager.java.
Referenced by SimulinkModelManager.testReplacExtension().
SimulinkModelManager (String modelPath)
Opens a simulink-ecore model from file.
Parameters:
modelPath
Definition at line 47 of file SimulinkModelManager.java.
SimulinkModelManager (URI model)
Opens a simulink-ecore model from the given model.
Parameters:
model
Definition at line 55 of file SimulinkModelManager.java.
References ModelManager.init(), and ModelManager.setFileExtension().
Member Function Documentation
SimulinkFactory getFactory ()
Returns:
the factory for this metamodel.
Reimplemented from ModelManager.
Definition at line 31 of file SimulinkModelManager.java.
Referenced by SimulinkModelManagerTest.testNewModel().
void initMetaModel () [protected, virtual]
Adds the metamodel the the global EMF registry and initializes the metamodel factory.
Implements ModelManager.
Definition at line 23 of file SimulinkModelManager.java.
References ModelManager.ePackage.
void testReplacExtension ()
Definition at line 62 of file SimulinkModelManager.java.
References ModelManager.replaceExtension(), and SimulinkModelManager.SimulinkModelManager().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelManagement/simulink/SimulinkModelManager.java