modelConversion: SimulinkEcoreCreator Class Reference
SimulinkEcoreCreator Class Reference
This is a convenience class to easily create ecore models.
Public Member Functions
SimulinkEcoreCreator (SimulinkFactory aFactory)
A convenience class to easily create ecore models.
Model newModel (String modelName)
Creates a model, the top element in the metamodel.
Model getTopElement ()
System addRootSystem (String name)
A System is obtained and treated as the root for this model.
System findSystem (String name)
SystemReference addSystem (PropertyList pList)
Adds a new instance of a system to the model, in the right place.
System addSystem (String name, System parent, String instanceName)
System addSystem (String name, System parent)
Inport addInPort (String name, System parent)
Adds an Inport to the given system.
Outport addOutPort (String name, System parent)
Adds an Outport to the given system.
Line addLineBetween (String lineName, System source, System destination, System parent)
Adds a line between the first outport of source and the first inport of destination.
Line addLine (String lineName, Port source, Port destination, System parent)
Adds a line between two ports.
void addLines (ArrayList< LineInfo > lines) throws PortNotFoundException
Adds all lines contained in lines.
System findSystem (UUID uuid)
SystemReference findSystemReference (UUID uuid)
Port findPort (UUID uuid)
Line findLine (UUID uuid)
Static Public Member Functions
static Port findPortWithin (String portName, System aSystem)
Find a given port within a system, and its first level children.
static Outport findOutportWithin (String portName, System aSystem)
TODO: Should this be private? Is MATLAB using this one directly?
static Inport findInportWithin (String portName, System aSystem)
TODO: Should this be private? Is MATLAB using this one directly?
Protected Attributes
SimulinkFactory factory
The factory for the simulink metamodel.
Model theModel
The top element.
HashMap< String, System > systemRepository
Keeps a reference to all systems created by this class.
HashMap< UUID, ProtoObject > repository
Keeps a reference to all elements created by this class.
Private Member Functions
void setUUIDAndAddToRepository (ProtoObject object)
This class keeps track of all elements it has created, with a UUID.
System obtainSystem (String name)
If the system is not already in the systemRepository, it will be created.
System newSystem (String name)
Creates a new system and ads it to the systemRepository.
SystemReference addSystemInstance (String name, System parent, String instanceName)
Adds a new SystemReference to this model, with all the appropriate links.
Static Private Member Functions
static EList< System > createSystemListWithParentAndFirstLevelChldren (System aSystem)
static EList< System > getAllTargets (EList< SystemReference > childrenList)
static Outport findOutportInSystem (String portName, System aSystem)
static Inport findInportInSystem (String portName, System aSystem)
static< IOPortextendsPort > IOPort findPortInList (String portName, EList< IOPort > ports)
Detailed Description
This is a convenience class to easily create ecore models.
It is mainly used from MATLAB, but it is useful if you want to build models programmatically for example, for testing purposes. This class keeps track of all elements it has created, with a UUID. TODO: Should it be renamed to EcoreFactory maybe?
Author:
Alex Schenkman
Definition at line 31 of file SimulinkEcoreCreator.java.
Constructor & Destructor Documentation
SimulinkEcoreCreator (SimulinkFactory aFactory)
A convenience class to easily create ecore models.
Parameters:
aFactory This can be obtained from a ModelManager.
Definition at line 42 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.factory, SimulinkEcoreCreator.repository, and SimulinkEcoreCreator.systemRepository.
Member Function Documentation
Inport addInPort (String name, System parent)
Adds an Inport to the given system.
Parameters:
name of the port.
parent the system where this port should be added.
Returns:
the newly created port.
Definition at line 274 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.factory, and SimulinkEcoreCreator.setUUIDAndAddToRepository().
Referenced by SimulinkDemoModelCreator.createF2Subsystems(), SimulinkDemoModelCreator.createF2System(), SimulinkDemoModelCreator.createF3System(), SimulinkEcoreCreatorTest.testAddLines(), SimulinkEcoreCreatorTest.testLines(), and SimulinkEcoreCreatorTest.testPorts().
Line addLine (String lineName, Port source, Port destination, System parent)
Adds a line between two ports.
Useful for tests.
Parameters:
lineName
source
destination
parent the system this line belongs to.
Returns:
the newly created line.
Definition at line 322 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.factory, and SimulinkEcoreCreator.setUUIDAndAddToRepository().
Referenced by SimulinkEcoreCreator.addLineBetween(), SimulinkEcoreCreator.addLines(), and SimulinkEcoreCreatorTest.testLines().
Line addLineBetween (String lineName, System source, System destination, System parent)
Adds a line between the first outport of source and the first inport of destination.
This is a convenience method to quickly create lines for tests.
Parameters:
lineName
source
destination
parent the system this line belongs to.
Returns:
the newly created line.
Definition at line 307 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.addLine().
Referenced by SimulinkDemoModelCreator.createLines().
void addLines (ArrayList< LineInfo > lines) throws PortNotFoundException
Adds all lines contained in lines.
This is the way MATLAB adds lines to a model. See LineInfo for mode information.
Parameters:
lines a list of lines, prepared by MATLAB.
Exceptions:
PortNotFoundException if port not found.
Definition at line 340 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.addLine(), and SimulinkEcoreCreator.findPort().
Referenced by SimulinkEcoreCreatorTest.testAddLines().
Outport addOutPort (String name, System parent)
Adds an Outport to the given system.
Parameters:
name of the port.
parent the system where this port should be added.
Returns:
the newly created port.
Definition at line 289 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.factory, and SimulinkEcoreCreator.setUUIDAndAddToRepository().
Referenced by SimulinkDemoModelCreator.createF1System(), SimulinkDemoModelCreator.createF2Subsystems(), SimulinkDemoModelCreator.createF2System(), SimulinkDemoModelCreator.createF3System(), SimulinkEcoreCreatorTest.testAddLines(), SimulinkEcoreCreatorTest.testLines(), and SimulinkEcoreCreatorTest.testPorts().
System addRootSystem (String name)
A System is obtained and treated as the root for this model.
Note that if a system with the same name has previously been created, it will be reused, instead of creating a new one.
Parameters:
name
Returns:
Definition at line 87 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.obtainSystem(), SimulinkEcoreCreator.setUUIDAndAddToRepository(), and SimulinkEcoreCreator.theModel.
Referenced by SimulinkDemoModelCreator.getNewModelAndNewFile(), and SimulinkEcoreCreatorTest.testRootSystem().
System addSystem (String name, System parent)
Definition at line 263 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.addSystem().
System addSystem (String name, System parent, String instanceName)
Definition at line 254 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.addSystemInstance().
SystemReference addSystem (PropertyList pList)
Adds a new instance of a system to the model, in the right place.
This is implemented as ModelReferences in MATLAB, but it might change to libraries. This is the preferred way of adding new systems, as it opens the possibility to exchange any given number of parameters.
Parameters:
pList the information needed to create a system instance.
Returns:
a newly created SystemReference.
Definition at line 223 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.addSystemInstance(), PropertyList.getInstanceName(), PropertyList.getName(), and PropertyList.getParent().
Referenced by SimulinkEcoreCreator.addSystem(), SimulinkDemoModelCreator.createF1System(), SimulinkDemoModelCreator.createF2Subsystems(), SimulinkDemoModelCreator.createF2System(), SimulinkDemoModelCreator.createF3System(), SimulinkEcoreCreatorTest.testAddSystemWithPList(), SimulinkEcoreCreatorTest.testChild(), SimulinkEcoreCreatorTest.testLines(), SimulinkEcoreCreatorTest.testReferences(), and SimulinkEcoreCreatorTest.testSystemContainment().
SystemReference addSystemInstance (String name, System parent, String instanceName) [private]
Adds a new SystemReference to this model, with all the appropriate links.
Parameters:
name of the system to instantiate.
parent the system that contains this instance.
instanceName the name this instance gets in MATLAB.
Returns:
a newly created SystemReference.
Definition at line 239 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.factory, SimulinkEcoreCreator.obtainSystem(), and SimulinkEcoreCreator.setUUIDAndAddToRepository().
Referenced by SimulinkEcoreCreator.addSystem().
static EList<System> createSystemListWithParentAndFirstLevelChldren (System aSystem) [static, private]
Parameters:
aSystem where to start the search.
Returns:
a list with aSystem and only, its first level children.
Definition at line 178 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.getAllTargets().
Referenced by SimulinkEcoreCreator.findInportWithin(), and SimulinkEcoreCreator.findOutportWithin().
static Inport findInportInSystem (String portName, System aSystem) [static, private]
Definition at line 200 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.findPortInList().
Referenced by SimulinkEcoreCreator.findInportWithin().
static Inport findInportWithin (String portName, System aSystem) [static]
TODO: Should this be private? Is MATLAB using this one directly?
Definition at line 163 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.createSystemListWithParentAndFirstLevelChldren(), and SimulinkEcoreCreator.findInportInSystem().
Referenced by SimulinkEcoreCreator.findPortWithin().
Line findLine (UUID uuid)
Definition at line 366 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.repository.
Referenced by SimulinkEcoreCreatorTest.testFindInRepository().
static Outport findOutportInSystem (String portName, System aSystem) [static, private]
Definition at line 196 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.findPortInList().
Referenced by SimulinkEcoreCreator.findOutportWithin().
static Outport findOutportWithin (String portName, System aSystem) [static]
TODO: Should this be private? Is MATLAB using this one directly?
Definition at line 149 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.createSystemListWithParentAndFirstLevelChldren(), and SimulinkEcoreCreator.findOutportInSystem().
Referenced by SimulinkEcoreCreator.findPortWithin().
Port findPort (UUID uuid)
Definition at line 362 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.repository.
Referenced by SimulinkEcoreCreator.addLines(), and SimulinkEcoreCreatorTest.testFindInRepository().
static <IOPortextendsPort> IOPort findPortInList (String portName, EList< IOPort > ports) [static, private]
Definition at line 204 of file SimulinkEcoreCreator.java.
Referenced by SimulinkEcoreCreator.findInportInSystem(), and SimulinkEcoreCreator.findOutportInSystem().
static Port findPortWithin (String portName, System aSystem) [static]
Find a given port within a system, and its first level children.
This is used by MATLAB when creating lines.
Parameters:
portName Name of the port.
aSystem Where to start looking.
Returns:
the port if found, null otherwise.
Definition at line 138 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.findInportWithin(), and SimulinkEcoreCreator.findOutportWithin().
System findSystem (UUID uuid)
Definition at line 354 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.repository.
System findSystem (String name)
Parameters:
name Name of the system to be found.
Returns:
the found system or null if not found.
Definition at line 127 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.systemRepository.
Referenced by SimulinkDemoModelCreator.createF2Subsystems(), SimulinkDemoModelCreator.createLines(), SimulinkEcoreCreator.obtainSystem(), SimulinkEcoreCreatorTest.testAddLines(), SimulinkEcoreCreatorTest.testFindInRepository(), SimulinkEcoreCreatorTest.testFindSystem(), and SimulinkEcoreCreatorTest.testReferences().
SystemReference findSystemReference (UUID uuid)
Definition at line 358 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.repository.
Referenced by SimulinkEcoreCreatorTest.testAddSystemWithPList().
static EList<System> getAllTargets (EList< SystemReference > childrenList) [static, private]
Definition at line 187 of file SimulinkEcoreCreator.java.
Referenced by SimulinkEcoreCreator.createSystemListWithParentAndFirstLevelChldren().
Model getTopElement ()
Returns:
the model element at the top of the hierarchy.
Definition at line 75 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.theModel.
Referenced by SimulinkDemoModelCreator.save(), SimulinkEcoreCreatorTest.testNewModel(), and SimulinkEcoreCreatorTest.testSystemContainment().
Model newModel (String modelName)
Creates a model, the top element in the metamodel.
Parameters:
modelName Name of the model.
Returns:
the newly created model,
Definition at line 53 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.factory, SimulinkEcoreCreator.setUUIDAndAddToRepository(), and SimulinkEcoreCreator.theModel.
Referenced by SimulinkDemoModelCreator.getNewModelAndNewFile(), and SimulinkEcoreCreatorTest.testNewModel().
System newSystem (String name) [private]
Creates a new system and ads it to the systemRepository.
Parameters:
name Name for the system to be created.
Returns:
the newly created system.
Definition at line 113 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.factory, SimulinkEcoreCreator.setUUIDAndAddToRepository(), SimulinkEcoreCreator.systemRepository, and SimulinkEcoreCreator.theModel.
Referenced by SimulinkEcoreCreator.obtainSystem().
System obtainSystem (String name) [private]
If the system is not already in the systemRepository, it will be created.
systems are identified by its name.
Definition at line 99 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.findSystem(), and SimulinkEcoreCreator.newSystem().
Referenced by SimulinkEcoreCreator.addRootSystem(), and SimulinkEcoreCreator.addSystemInstance().
void setUUIDAndAddToRepository (ProtoObject object) [private]
This class keeps track of all elements it has created, with a UUID.
This allows to easily find elements given the UUID, which is stored by Simulink as well.
Parameters:
object A UUID will be set for this object.
Definition at line 65 of file SimulinkEcoreCreator.java.
References SimulinkEcoreCreator.repository.
Referenced by SimulinkEcoreCreator.addInPort(), SimulinkEcoreCreator.addLine(), SimulinkEcoreCreator.addOutPort(), SimulinkEcoreCreator.addRootSystem(), SimulinkEcoreCreator.addSystemInstance(), SimulinkEcoreCreator.newModel(), and SimulinkEcoreCreator.newSystem().
Member Data Documentation
SimulinkFactory factory [protected]
The factory for the simulink metamodel.
Definition at line 33 of file SimulinkEcoreCreator.java.
Referenced by SimulinkEcoreCreator.addInPort(), SimulinkEcoreCreator.addLine(), SimulinkEcoreCreator.addOutPort(), SimulinkEcoreCreator.addSystemInstance(), SimulinkEcoreCreator.newModel(), SimulinkEcoreCreator.newSystem(), and SimulinkEcoreCreator.SimulinkEcoreCreator().
HashMap<UUID, ProtoObject> repository [protected]
Keeps a reference to all elements created by this class.
Definition at line 36 of file SimulinkEcoreCreator.java.
Referenced by SimulinkEcoreCreator.findLine(), SimulinkEcoreCreator.findPort(), SimulinkEcoreCreator.findSystem(), SimulinkEcoreCreator.findSystemReference(), SimulinkEcoreCreator.setUUIDAndAddToRepository(), and SimulinkEcoreCreator.SimulinkEcoreCreator().
HashMap<String, System> systemRepository [protected]
Keeps a reference to all systems created by this class.
Definition at line 35 of file SimulinkEcoreCreator.java.
Referenced by SimulinkEcoreCreator.findSystem(), SimulinkEcoreCreator.newSystem(), and SimulinkEcoreCreator.SimulinkEcoreCreator().
Model theModel [protected]
The top element.
Definition at line 34 of file SimulinkEcoreCreator.java.
Referenced by SimulinkEcoreCreator.addRootSystem(), SimulinkEcoreCreator.getTopElement(), SimulinkEcoreCreator.newModel(), and SimulinkEcoreCreator.newSystem().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/SimulinkEcoreCreator.java