modelConversion: LineInfo Class Reference
LineInfo Class Reference
Public Member Functions
LineInfo (System lineParent)
void setName (String name)
String getName ()
System getLineParent ()
void setSrcPort (String uuidStr)
void setSrcPort (UUID srcPort)
UUID getSrcPort ()
void setDstPort (String uuidStr)
void setDstPort (UUID dstPort)
UUID getDstPort ()
Static Public Member Functions
static ArrayList< LineInfo > createArray ()
Public Attributes
String lineName
UUID srcPort
UUID dstPort
System lineParent
Detailed Description
Definition at line 9 of file LineInfo.java.
Constructor & Destructor Documentation
LineInfo (System lineParent)
Definition at line 18 of file LineInfo.java.
Member Function Documentation
static ArrayList<LineInfo> createArray () [static]
Definition at line 34 of file LineInfo.java.
UUID getDstPort ()
Definition at line 62 of file LineInfo.java.
References LineInfo.dstPort.
System getLineParent ()
Definition at line 38 of file LineInfo.java.
References LineInfo.lineParent.
String getName ()
Definition at line 26 of file LineInfo.java.
References LineInfo.lineName.
UUID getSrcPort ()
Definition at line 50 of file LineInfo.java.
References LineInfo.srcPort.
void setDstPort (UUID dstPort)
Definition at line 58 of file LineInfo.java.
void setDstPort (String uuidStr)
Definition at line 54 of file LineInfo.java.
Referenced by SimulinkEcoreCreatorTest.testAddLines().
void setName (String name)
Definition at line 22 of file LineInfo.java.
References LineInfo.lineName.
Referenced by SimulinkEcoreCreatorTest.testAddLines().
void setSrcPort (UUID srcPort)
Definition at line 46 of file LineInfo.java.
void setSrcPort (String uuidStr)
Definition at line 42 of file LineInfo.java.
Referenced by SimulinkEcoreCreatorTest.testAddLines().
Member Data Documentation
UUID dstPort
Definition at line 13 of file LineInfo.java.
Referenced by LineInfo.getDstPort().
String lineName
Definition at line 11 of file LineInfo.java.
Referenced by LineInfo.getName(), and LineInfo.setName().
System lineParent
Definition at line 14 of file LineInfo.java.
Referenced by LineInfo.getLineParent().
UUID srcPort
Definition at line 12 of file LineInfo.java.
Referenced by LineInfo.getSrcPort().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/LineInfo.java