modelConversion: ModelProcessor Class Reference
ModelProcessor Class Reference
Adds the model as the first element in the list, and lets the root system continue.
Static Public Member Functions
static ArrayList< ProtoObject > doIt (Model aModel)
This is the entry point for the package.
Package Attributes
Model theModel
ArrayList< ProtoObject > allElements = new ArrayList<ProtoObject>()
Private Member Functions
ArrayList< ProtoObject > process ()
void computeSimulinkName ()
Detailed Description
Adds the model as the first element in the list, and lets the root system continue.
Author:
Alex Schenkman
Definition at line 23 of file ModelProcessor.java.
Member Function Documentation
void computeSimulinkName () [private]
Definition at line 51 of file ModelProcessor.java.
References ModelProcessor.theModel.
Referenced by ModelProcessor.process().
static ArrayList<ProtoObject> doIt (Model aModel) [static]
This is the entry point for the package.
Parameters:
aModel the model to be processed (flattened and completed)
Returns:
a list with all elements, ready to be parsed by MATLAB.
Definition at line 33 of file ModelProcessor.java.
References ModelProcessor.process(), and ModelProcessor.theModel.
ArrayList<ProtoObject> process () [private]
Definition at line 40 of file ModelProcessor.java.
References ModelProcessor.allElements, ModelProcessor.computeSimulinkName(), and ModelProcessor.theModel.
Referenced by ModelProcessor.doIt().
Member Data Documentation
ArrayList<ProtoObject> allElements = new ArrayList<ProtoObject>() [package]
Definition at line 26 of file ModelProcessor.java.
Referenced by ModelProcessor.process().
Model theModel [package]
Definition at line 25 of file ModelProcessor.java.
Referenced by ModelProcessor.computeSimulinkName(), ModelProcessor.doIt(), and ModelProcessor.process().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/preprocessing/ModelProcessor.java