modelConversion: SimulinkEcoreCreatorTest Class Reference
SimulinkEcoreCreatorTest Class Reference
Public Member Functions
void testSimulinkEcoreCreator ()
Model testNewModel ()
System testRootSystem (Model aModel)
System testFindSystem (System rootSystem)
System testChild (System rootSystem)
System testReferences (System aSystem)
System testSystemContainment (System aSystem)
System testPorts (System aSystem)
System testLines (System parent)
System testFindPorts (System parent)
System testAddLines (System parent)
System testPortNotFound (System parent)
System testAddSystemWithPList (System parent)
System testFindInRepository (System parent)
Private Attributes
SimulinkModelManager modelManager
SimulinkEcoreCreator simulinkEcoreCreator
Detailed Description
Definition at line 32 of file SimulinkEcoreCreatorTest.java.
Member Function Documentation
System testAddLines (System parent)
Definition at line 149 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.addInPort(), SimulinkEcoreCreator.addLines(), SimulinkEcoreCreator.addOutPort(), SimulinkEcoreCreator.findSystem(), LineInfo.setDstPort(), LineInfo.setName(), and LineInfo.setSrcPort().
System testAddSystemWithPList (System parent)
Definition at line 218 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.addSystem(), and SimulinkEcoreCreator.findSystemReference().
System testChild (System rootSystem)
Definition at line 71 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.addSystem().
System testFindInRepository (System parent)
Definition at line 229 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.findLine(), SimulinkEcoreCreator.findPort(), and SimulinkEcoreCreator.findSystem().
System testFindPorts (System parent)
Definition at line 131 of file SimulinkEcoreCreatorTest.java.
System testFindSystem (System rootSystem)
Definition at line 63 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.findSystem().
System testLines (System parent)
Definition at line 116 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.addInPort(), SimulinkEcoreCreator.addLine(), SimulinkEcoreCreator.addOutPort(), and SimulinkEcoreCreator.addSystem().
Model testNewModel ()
Definition at line 47 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.getTopElement(), and SimulinkEcoreCreator.newModel().
System testPortNotFound (System parent)
Definition at line 191 of file SimulinkEcoreCreatorTest.java.
System testPorts (System aSystem)
Definition at line 101 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.addInPort(), and SimulinkEcoreCreator.addOutPort().
System testReferences (System aSystem)
Definition at line 80 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.addSystem(), and SimulinkEcoreCreator.findSystem().
System testRootSystem (Model aModel)
Definition at line 55 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.addRootSystem().
void testSimulinkEcoreCreator ()
Definition at line 38 of file SimulinkEcoreCreatorTest.java.
System testSystemContainment (System aSystem)
Definition at line 90 of file SimulinkEcoreCreatorTest.java.
References SimulinkEcoreCreator.addSystem(), and SimulinkEcoreCreator.getTopElement().
Member Data Documentation
SimulinkModelManager modelManager [private]
Definition at line 34 of file SimulinkEcoreCreatorTest.java.
SimulinkEcoreCreator simulinkEcoreCreator [private]
Definition at line 35 of file SimulinkEcoreCreatorTest.java.
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/SimulinkEcoreCreatorTest.java