modelConversion: SimulinkDemoModelCreator Class Reference
SimulinkDemoModelCreator Class Reference
Static Public Member Functions
static void main (String[] args)
Package Attributes
String pathName = "testWorkspace/demo.simulink"
SimulinkModelManager modelManager
SimulinkEcoreCreator simulinkEcoreCreator
System root
Private Member Functions
void save ()
void createLines ()
void createF1System ()
void createF2System ()
void createF2Subsystems ()
void createF3System ()
void getNewModelAndNewFile ()
Detailed Description
Definition at line 10 of file SimulinkDemoModelCreator.java.
Member Function Documentation
void createF1System () [private]
Definition at line 52 of file SimulinkDemoModelCreator.java.
References SimulinkEcoreCreator.addOutPort(), SimulinkEcoreCreator.addSystem(), SimulinkDemoModelCreator.root, and SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by SimulinkDemoModelCreator.main().
void createF2Subsystems () [private]
Definition at line 63 of file SimulinkDemoModelCreator.java.
References SimulinkEcoreCreator.addInPort(), SimulinkEcoreCreator.addOutPort(), SimulinkEcoreCreator.addSystem(), SimulinkEcoreCreator.findSystem(), and SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by SimulinkDemoModelCreator.main().
void createF2System () [private]
Definition at line 57 of file SimulinkDemoModelCreator.java.
References SimulinkEcoreCreator.addInPort(), SimulinkEcoreCreator.addOutPort(), SimulinkEcoreCreator.addSystem(), SimulinkDemoModelCreator.root, and SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by SimulinkDemoModelCreator.main().
void createF3System () [private]
Definition at line 74 of file SimulinkDemoModelCreator.java.
References SimulinkEcoreCreator.addInPort(), SimulinkEcoreCreator.addOutPort(), SimulinkEcoreCreator.addSystem(), SimulinkDemoModelCreator.root, and SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by SimulinkDemoModelCreator.main().
void createLines () [private]
Definition at line 41 of file SimulinkDemoModelCreator.java.
References SimulinkEcoreCreator.addLineBetween(), SimulinkEcoreCreator.findSystem(), SimulinkDemoModelCreator.root, and SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by SimulinkDemoModelCreator.main().
void getNewModelAndNewFile () [private]
Definition at line 80 of file SimulinkDemoModelCreator.java.
References SimulinkEcoreCreator.addRootSystem(), SimulinkDemoModelCreator.modelManager, SimulinkEcoreCreator.newModel(), SimulinkDemoModelCreator.pathName, SimulinkDemoModelCreator.root, and SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by SimulinkDemoModelCreator.main().
static void main (String[] args) [static]
Definition at line 17 of file SimulinkDemoModelCreator.java.
References SimulinkDemoModelCreator.createF1System(), SimulinkDemoModelCreator.createF2Subsystems(), SimulinkDemoModelCreator.createF2System(), SimulinkDemoModelCreator.createF3System(), SimulinkDemoModelCreator.createLines(), SimulinkDemoModelCreator.getNewModelAndNewFile(), and SimulinkDemoModelCreator.save().
void save () [private]
Definition at line 28 of file SimulinkDemoModelCreator.java.
References SimulinkEcoreCreator.getTopElement(), SimulinkDemoModelCreator.modelManager, and SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by SimulinkDemoModelCreator.main().
Member Data Documentation
SimulinkModelManager modelManager [package]
Definition at line 13 of file SimulinkDemoModelCreator.java.
Referenced by SimulinkDemoModelCreator.getNewModelAndNewFile(), and SimulinkDemoModelCreator.save().
String pathName = "testWorkspace/demo.simulink" [package]
Definition at line 12 of file SimulinkDemoModelCreator.java.
Referenced by SimulinkDemoModelCreator.getNewModelAndNewFile().
System root [package]
Definition at line 15 of file SimulinkDemoModelCreator.java.
Referenced by SimulinkDemoModelCreator.createF1System(), SimulinkDemoModelCreator.createF2System(), SimulinkDemoModelCreator.createF3System(), SimulinkDemoModelCreator.createLines(), and SimulinkDemoModelCreator.getNewModelAndNewFile().
SimulinkEcoreCreator simulinkEcoreCreator [package]
Definition at line 14 of file SimulinkDemoModelCreator.java.
Referenced by SimulinkDemoModelCreator.createF1System(), SimulinkDemoModelCreator.createF2Subsystems(), SimulinkDemoModelCreator.createF2System(), SimulinkDemoModelCreator.createF3System(), SimulinkDemoModelCreator.createLines(), SimulinkDemoModelCreator.getNewModelAndNewFile(), and SimulinkDemoModelCreator.save().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/SimulinkDemoModelCreator.java