modelConversion: SystemProcessor Class Reference
SystemProcessor Class Reference
Static Public Member Functions
static Collection<?extends
ProtoObject > doIt (System aSystem)
Package Attributes
System theSystem
Static Package Attributes
static HashSet< System > sysRepository = new HashSet<System>()
Private Member Functions
Collection<?extends ProtoObject > process ()
void createSystem (ArrayList< ProtoObject > list)
void computeSimulinkName ()
void computeFileName ()
Detailed Description
Definition at line 11 of file SystemProcessor.java.
Member Function Documentation
void computeFileName () [private]
Definition at line 49 of file SystemProcessor.java.
References SystemProcessor.theSystem.
Referenced by SystemProcessor.createSystem().
void computeSimulinkName () [private]
Definition at line 45 of file SystemProcessor.java.
References SystemProcessor.theSystem.
Referenced by SystemProcessor.createSystem().
void createSystem (ArrayList< ProtoObject > list) [private]
Definition at line 32 of file SystemProcessor.java.
References SystemProcessor.computeFileName(), SystemProcessor.computeSimulinkName(), and SystemProcessor.theSystem.
Referenced by SystemProcessor.process().
static Collection<? extends ProtoObject> doIt (System aSystem) [static]
Definition at line 16 of file SystemProcessor.java.
References SystemProcessor.process(), and SystemProcessor.theSystem.
Collection<? extends ProtoObject> process () [private]
Definition at line 22 of file SystemProcessor.java.
References SystemProcessor.createSystem(), SystemProcessor.sysRepository, and SystemProcessor.theSystem.
Referenced by SystemProcessor.doIt().
Member Data Documentation
HashSet<System> sysRepository = new HashSet<System>() [static, package]
Definition at line 14 of file SystemProcessor.java.
Referenced by SystemProcessor.process().
System theSystem [package]
Definition at line 13 of file SystemProcessor.java.
Referenced by SystemProcessor.computeFileName(), SystemProcessor.computeSimulinkName(), SystemProcessor.createSystem(), SystemProcessor.doIt(), and SystemProcessor.process().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/preprocessing/SystemProcessor.java