modelConversion: LinesProcessor Class Reference
LinesProcessor Class Reference
Static Public Member Functions
static Collection<?extends
ProtoObject > doIt (System aSystem)
Package Attributes
System theSystem
Private Member Functions
Collection<?extends ProtoObject > process ()
void process (Line aLine)
String processPort (Line aLine, Port port)
Integer findPosInBlock (System aSystem, Port port)
System obtainPortParent (Port port)
SystemReference findBlockNameWithinReferences (Line aLine, System portParentSys)
boolean portBelongsToSubsystem (Line aLine, System portParentSys)
Detailed Description
Definition at line 14 of file LinesProcessor.java.
Member Function Documentation
static Collection<? extends ProtoObject> doIt (System aSystem) [static]
Definition at line 18 of file LinesProcessor.java.
References LinesProcessor.process(), and LinesProcessor.theSystem.
SystemReference findBlockNameWithinReferences (Line aLine, System portParentSys) [private]
Definition at line 78 of file LinesProcessor.java.
Referenced by LinesProcessor.processPort().
Integer findPosInBlock (System aSystem, Port port) [private]
Definition at line 55 of file LinesProcessor.java.
Referenced by LinesProcessor.processPort().
System obtainPortParent (Port port) [private]
Definition at line 63 of file LinesProcessor.java.
Referenced by LinesProcessor.processPort().
boolean portBelongsToSubsystem (Line aLine, System portParentSys) [private]
Definition at line 87 of file LinesProcessor.java.
Referenced by LinesProcessor.processPort().
void process (Line aLine) [private]
Definition at line 34 of file LinesProcessor.java.
References LinesProcessor.processPort().
Collection<? extends ProtoObject> process () [private]
Definition at line 25 of file LinesProcessor.java.
References LinesProcessor.theSystem.
Referenced by LinesProcessor.doIt().
String processPort (Line aLine, Port port) [private]
Definition at line 43 of file LinesProcessor.java.
References LinesProcessor.findBlockNameWithinReferences(), LinesProcessor.findPosInBlock(), LinesProcessor.obtainPortParent(), and LinesProcessor.portBelongsToSubsystem().
Referenced by LinesProcessor.process().
Member Data Documentation
System theSystem [package]
Definition at line 16 of file LinesProcessor.java.
Referenced by LinesProcessor.doIt(), and LinesProcessor.process().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/preprocessing/LinesProcessor.java