modelConversion: SysRefsProcessor Class Reference
SysRefsProcessor Class Reference
Static Public Member Functions
static Collection<?extends
ProtoObject > doIt (System aSystem, SystemLayouter layouter)
Package Attributes
ArrayList< ProtoObject > list = new ArrayList<ProtoObject>()
System theSystem
SystemLayouter layouter
Private Member Functions
Collection<?extends ProtoObject > process ()
void processSystemReference (SystemReference sysRef)
void computePosition (SystemReference sysRef)
void computeInstanceName (SystemReference sysRef)
Detailed Description
Definition at line 11 of file SysRefsProcessor.java.
Member Function Documentation
void computeInstanceName (SystemReference sysRef) [private]
Definition at line 54 of file SysRefsProcessor.java.
Referenced by SysRefsProcessor.processSystemReference().
void computePosition (SystemReference sysRef) [private]
Definition at line 45 of file SysRefsProcessor.java.
References SysRefsProcessor.layouter, and SystemLayouter.nextSystem().
Referenced by SysRefsProcessor.processSystemReference().
static Collection<? extends ProtoObject> doIt (System aSystem, SystemLayouter layouter) [static]
Definition at line 17 of file SysRefsProcessor.java.
References SysRefsProcessor.layouter, SysRefsProcessor.process(), and SysRefsProcessor.theSystem.
Collection<? extends ProtoObject> process () [private]
Definition at line 28 of file SysRefsProcessor.java.
References SysRefsProcessor.layouter, SysRefsProcessor.list, SysRefsProcessor.processSystemReference(), SystemLayouter.startWithSystems(), and SysRefsProcessor.theSystem.
Referenced by SysRefsProcessor.doIt().
void processSystemReference (SystemReference sysRef) [private]
Definition at line 37 of file SysRefsProcessor.java.
References SysRefsProcessor.computeInstanceName(), SysRefsProcessor.computePosition(), and SysRefsProcessor.list.
Referenced by SysRefsProcessor.process().
Member Data Documentation
SystemLayouter layouter [package]
Definition at line 15 of file SysRefsProcessor.java.
Referenced by SysRefsProcessor.computePosition(), SysRefsProcessor.doIt(), and SysRefsProcessor.process().
ArrayList<ProtoObject> list = new ArrayList<ProtoObject>() [package]
Definition at line 13 of file SysRefsProcessor.java.
Referenced by SysRefsProcessor.process(), and SysRefsProcessor.processSystemReference().
System theSystem [package]
Definition at line 14 of file SysRefsProcessor.java.
Referenced by SysRefsProcessor.doIt(), and SysRefsProcessor.process().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/preprocessing/SysRefsProcessor.java