modelConversion: SystemLayouter Class Reference
SystemLayouter Class Reference
Public Member Functions
void startWithSystems ()
void startWithOutports ()
String nextPort ()
String nextSystem ()
Package Attributes
final Integer distanceBetweenPorts = new Integer(60)
final Integer distanceBetweenSystmes = new Integer(90)
final Integer blockSizeHoriz = new Integer(250)
final Integer blockSizeVert = new Integer(100)
final Integer portSizeHoriz = new Integer(30)
final Integer portSizeVert = new Integer(14)
Private Member Functions
String buildPositionString ()
Private Attributes
Integer top = new Integer(40)
Integer left = new Integer(35)
Integer bottom = new Integer(0)
Integer right = new Integer(0)
Detailed Description
Definition at line 8 of file SystemLayouter.java.
Member Function Documentation
String buildPositionString () [private]
Definition at line 49 of file SystemLayouter.java.
References SystemLayouter.bottom, SystemLayouter.left, SystemLayouter.right, and SystemLayouter.top.
Referenced by SystemLayouter.nextPort(), and SystemLayouter.nextSystem().
String nextPort ()
Definition at line 33 of file SystemLayouter.java.
References SystemLayouter.bottom, SystemLayouter.buildPositionString(), SystemLayouter.distanceBetweenPorts, SystemLayouter.left, SystemLayouter.portSizeHoriz, SystemLayouter.portSizeVert, SystemLayouter.right, and SystemLayouter.top.
Referenced by PortProcessor.computePosition().
String nextSystem ()
Definition at line 41 of file SystemLayouter.java.
References SystemLayouter.blockSizeHoriz, SystemLayouter.blockSizeVert, SystemLayouter.bottom, SystemLayouter.buildPositionString(), SystemLayouter.distanceBetweenSystmes, SystemLayouter.left, SystemLayouter.right, and SystemLayouter.top.
Referenced by SysRefsProcessor.computePosition().
void startWithOutports ()
Definition at line 27 of file SystemLayouter.java.
References SystemLayouter.blockSizeHoriz, SystemLayouter.distanceBetweenSystmes, SystemLayouter.left, and SystemLayouter.top.
Referenced by OutportsProcessor.doIt().
void startWithSystems ()
Definition at line 22 of file SystemLayouter.java.
References SystemLayouter.left, and SystemLayouter.top.
Referenced by SysRefsProcessor.process().
Member Data Documentation
final Integer blockSizeHoriz = new Integer(250) [package]
Definition at line 12 of file SystemLayouter.java.
Referenced by SystemLayouter.nextSystem(), and SystemLayouter.startWithOutports().
final Integer blockSizeVert = new Integer(100) [package]
Definition at line 13 of file SystemLayouter.java.
Referenced by SystemLayouter.nextSystem().
Integer bottom = new Integer(0) [private]
Definition at line 19 of file SystemLayouter.java.
Referenced by SystemLayouter.buildPositionString(), SystemLayouter.nextPort(), and SystemLayouter.nextSystem().
final Integer distanceBetweenPorts = new Integer(60) [package]
Definition at line 10 of file SystemLayouter.java.
Referenced by SystemLayouter.nextPort().
final Integer distanceBetweenSystmes = new Integer(90) [package]
Definition at line 11 of file SystemLayouter.java.
Referenced by SystemLayouter.nextSystem(), and SystemLayouter.startWithOutports().
Integer left = new Integer(35) [private]
Definition at line 18 of file SystemLayouter.java.
Referenced by SystemLayouter.buildPositionString(), SystemLayouter.nextPort(), SystemLayouter.nextSystem(), SystemLayouter.startWithOutports(), and SystemLayouter.startWithSystems().
final Integer portSizeHoriz = new Integer(30) [package]
Definition at line 14 of file SystemLayouter.java.
Referenced by SystemLayouter.nextPort().
final Integer portSizeVert = new Integer(14) [package]
Definition at line 15 of file SystemLayouter.java.
Referenced by SystemLayouter.nextPort().
Integer right = new Integer(0) [private]
Definition at line 20 of file SystemLayouter.java.
Referenced by SystemLayouter.buildPositionString(), SystemLayouter.nextPort(), and SystemLayouter.nextSystem().
Integer top = new Integer(40) [private]
Definition at line 17 of file SystemLayouter.java.
Referenced by SystemLayouter.buildPositionString(), SystemLayouter.nextPort(), SystemLayouter.nextSystem(), SystemLayouter.startWithOutports(), and SystemLayouter.startWithSystems().
The documentation for this class was generated from the following file:
src/se/kth/md/simulinkExchange/modelConversion/simulink/preprocessing/SystemLayouter.java