<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Simulink"
    nsURI="http:///se.kth.md.attest2/Simulink/3.0" nsPrefix="sim">
  <eClassifiers xsi:type="ecore:EClass" name="ProtoObject" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//ProtoObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inport" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//System" eOpposite="#//System/inports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Line" eOpposite="#//Line/destination"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Outport" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//System" eOpposite="#//System/outports"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Line" eOpposite="#//Line/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//ProtoObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" unique="false"
        lowerBound="1" eType="#//Outport" eOpposite="#//Outport/connections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" unique="false"
        lowerBound="1" eType="#//Inport" eOpposite="#//Inport/connections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//System" eOpposite="#//System/lines"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//ProtoObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//SystemReference" containment="true" eOpposite="#//SystemReference/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//Line" containment="true" eOpposite="#//Line/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inports" upperBound="-1"
        eType="#//Inport" containment="true" eOpposite="#//Inport/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outports" upperBound="-1"
        eType="#//Outport" containment="true" eOpposite="#//Outport/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//ProtoObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//System"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemReference" eSuperTypes="#//ProtoObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//System"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//System" eOpposite="#//System/children"/>
  </eClassifiers>
</ecore:EPackage>
