Carlota: modelManagement.test.SimulinkDemoModelCreator Class Reference
modelManagement.test.SimulinkDemoModelCreator Class Reference
Static Public Member Functions
static void main (String[] args)
Package Attributes
String pathName = "testWorkspace/demo.simulink"
SimulinkModelManager modelManager
SimulinkEcoreCreator simulinkEcoreCreator
System root
Private Member Functions
void save ()
void createLines ()
void createF1System ()
void createF2System ()
void createF2Subsystems ()
void createF3System ()
void getNewModelAndNewFile ()
Detailed Description
Definition at line 10 of file SimulinkDemoModelCreator.java.
Member Function Documentation
void modelManagement.test.SimulinkDemoModelCreator.createF1System () [private]
Definition at line 52 of file SimulinkDemoModelCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addOutPort(), modelManagement.simulink.SimulinkEcoreCreator.addSystem(), modelManagement.test.SimulinkDemoModelCreator.root, and modelManagement.test.SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by modelManagement.test.SimulinkDemoModelCreator.main().
void modelManagement.test.SimulinkDemoModelCreator.createF2Subsystems () [private]
Definition at line 63 of file SimulinkDemoModelCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addInPort(), modelManagement.simulink.SimulinkEcoreCreator.addOutPort(), modelManagement.simulink.SimulinkEcoreCreator.addSystem(), modelManagement.simulink.SimulinkEcoreCreator.findSystem(), and modelManagement.test.SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by modelManagement.test.SimulinkDemoModelCreator.main().
void modelManagement.test.SimulinkDemoModelCreator.createF2System () [private]
Definition at line 57 of file SimulinkDemoModelCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addInPort(), modelManagement.simulink.SimulinkEcoreCreator.addOutPort(), modelManagement.simulink.SimulinkEcoreCreator.addSystem(), modelManagement.test.SimulinkDemoModelCreator.root, and modelManagement.test.SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by modelManagement.test.SimulinkDemoModelCreator.main().
void modelManagement.test.SimulinkDemoModelCreator.createF3System () [private]
Definition at line 74 of file SimulinkDemoModelCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addInPort(), modelManagement.simulink.SimulinkEcoreCreator.addOutPort(), modelManagement.simulink.SimulinkEcoreCreator.addSystem(), modelManagement.test.SimulinkDemoModelCreator.root, and modelManagement.test.SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by modelManagement.test.SimulinkDemoModelCreator.main().
void modelManagement.test.SimulinkDemoModelCreator.createLines () [private]
Definition at line 41 of file SimulinkDemoModelCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addLineBetween(), modelManagement.simulink.SimulinkEcoreCreator.findSystem(), modelManagement.test.SimulinkDemoModelCreator.root, and modelManagement.test.SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by modelManagement.test.SimulinkDemoModelCreator.main().
void modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile () [private]
Definition at line 80 of file SimulinkDemoModelCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addRootSystem(), modelManagement.simulink.SimulinkModelManager.getFactory(), modelManagement.test.SimulinkDemoModelCreator.modelManager, modelManagement.simulink.SimulinkEcoreCreator.newModel(), modelManagement.test.SimulinkDemoModelCreator.pathName, modelManagement.test.SimulinkDemoModelCreator.root, and modelManagement.test.SimulinkDemoModelCreator.simulinkEcoreCreator.
Referenced by modelManagement.test.SimulinkDemoModelCreator.main().
static void modelManagement.test.SimulinkDemoModelCreator.main (String[] args) [static]
Definition at line 17 of file SimulinkDemoModelCreator.java.
References modelManagement.test.SimulinkDemoModelCreator.createF1System(), modelManagement.test.SimulinkDemoModelCreator.createF2Subsystems(), modelManagement.test.SimulinkDemoModelCreator.createF2System(), modelManagement.test.SimulinkDemoModelCreator.createF3System(), modelManagement.test.SimulinkDemoModelCreator.createLines(), modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile(), and modelManagement.test.SimulinkDemoModelCreator.save().
void modelManagement.test.SimulinkDemoModelCreator.save () [private]
Definition at line 28 of file SimulinkDemoModelCreator.java.
References modelManagement.exceptions.InvalidModelException.dumpInvalidObjectsToConsole(), modelManagement.simulink.SimulinkEcoreCreator.getTopElement(), modelManagement.test.SimulinkDemoModelCreator.modelManager, modelManagement.ModelManager.saveIt(), modelManagement.ModelManager.setTopElement(), modelManagement.test.SimulinkDemoModelCreator.simulinkEcoreCreator, and modelManagement.ModelManager.validateIt().
Referenced by modelManagement.test.SimulinkDemoModelCreator.main().
Member Data Documentation
SimulinkModelManager modelManagement.test.SimulinkDemoModelCreator.modelManager [package]
Definition at line 13 of file SimulinkDemoModelCreator.java.
Referenced by modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile(), and modelManagement.test.SimulinkDemoModelCreator.save().
String modelManagement.test.SimulinkDemoModelCreator.pathName = "testWorkspace/demo.simulink" [package]
Definition at line 12 of file SimulinkDemoModelCreator.java.
Referenced by modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile().
System modelManagement.test.SimulinkDemoModelCreator.root [package]
Definition at line 15 of file SimulinkDemoModelCreator.java.
Referenced by modelManagement.test.SimulinkDemoModelCreator.createF1System(), modelManagement.test.SimulinkDemoModelCreator.createF2System(), modelManagement.test.SimulinkDemoModelCreator.createF3System(), modelManagement.test.SimulinkDemoModelCreator.createLines(), and modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile().
SimulinkEcoreCreator modelManagement.test.SimulinkDemoModelCreator.simulinkEcoreCreator [package]
Definition at line 14 of file SimulinkDemoModelCreator.java.
Referenced by modelManagement.test.SimulinkDemoModelCreator.createF1System(), modelManagement.test.SimulinkDemoModelCreator.createF2Subsystems(), modelManagement.test.SimulinkDemoModelCreator.createF2System(), modelManagement.test.SimulinkDemoModelCreator.createF3System(), modelManagement.test.SimulinkDemoModelCreator.createLines(), modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile(), and modelManagement.test.SimulinkDemoModelCreator.save().
The documentation for this class was generated from the following file:
src/modelManagement/test/SimulinkDemoModelCreator.java