Carlota: modelManagement.test.EastModelManagerTest Class Reference
modelManagement.test.EastModelManagerTest Class Reference
Public Member Functions
void testValid () throws InvalidModelException
Static Public Member Functions
static void main (String[] args) throws InvalidModelException
Private Attributes
String modelPath = "../ATLtrafos/testFiles/MyEASTModel1.uml"
URI modelURI = URI.createFileURI(modelPath)
Detailed Description
Definition at line 10 of file EastModelManagerTest.java.
Member Function Documentation
static void modelManagement.test.EastModelManagerTest.main (String[] args) throws InvalidModelException [static]
Definition at line 22 of file EastModelManagerTest.java.
References modelManagement.test.EastModelManagerTest.testValid().
void modelManagement.test.EastModelManagerTest.testValid () throws InvalidModelException
Definition at line 15 of file EastModelManagerTest.java.
References modelManagement.ModelManager.loadIt(), modelManagement.test.EastModelManagerTest.modelURI, and modelManagement.ModelManager.validateIt().
Referenced by modelManagement.test.EastModelManagerTest.main().
Member Data Documentation
String modelManagement.test.EastModelManagerTest.modelPath = "../ATLtrafos/testFiles/MyEASTModel1.uml" [private]
Definition at line 12 of file EastModelManagerTest.java.
URI modelManagement.test.EastModelManagerTest.modelURI = URI.createFileURI(modelPath) [private]
Definition at line 13 of file EastModelManagerTest.java.
Referenced by modelManagement.test.EastModelManagerTest.testValid().
The documentation for this class was generated from the following file:
src/modelManagement/test/EastModelManagerTest.java