Carlota: modelManagement.simulink.SystemProcessor Class Reference
modelManagement.simulink.SystemProcessor Class Reference
Static Public Member Functions
static Collection<?extends
ProtoObject > doIt (System aSystem)
Package Attributes
System theSystem
Static Package Attributes
static HashSet< System > sysRepository = new HashSet<System>()
Private Member Functions
Collection<?extends ProtoObject > process ()
void createSystem (ArrayList< ProtoObject > list)
void computeSimulinkName ()
void computeFileName ()
Detailed Description
Definition at line 10 of file SystemProcessor.java.
Member Function Documentation
void modelManagement.simulink.SystemProcessor.computeFileName () [private]
Definition at line 48 of file SystemProcessor.java.
References modelManagement.simulink.SystemProcessor.theSystem.
Referenced by modelManagement.simulink.SystemProcessor.createSystem().
void modelManagement.simulink.SystemProcessor.computeSimulinkName () [private]
Definition at line 44 of file SystemProcessor.java.
References modelManagement.simulink.SystemProcessor.theSystem.
Referenced by modelManagement.simulink.SystemProcessor.createSystem().
void modelManagement.simulink.SystemProcessor.createSystem (ArrayList< ProtoObject > list) [private]
Definition at line 31 of file SystemProcessor.java.
References modelManagement.simulink.SystemProcessor.computeFileName(), modelManagement.simulink.SystemProcessor.computeSimulinkName(), and modelManagement.simulink.SystemProcessor.theSystem.
Referenced by modelManagement.simulink.SystemProcessor.process().
static Collection<? extends ProtoObject> modelManagement.simulink.SystemProcessor.doIt (System aSystem) [static]
Definition at line 15 of file SystemProcessor.java.
References modelManagement.simulink.SystemProcessor.process(), and modelManagement.simulink.SystemProcessor.theSystem.
Collection<? extends ProtoObject> modelManagement.simulink.SystemProcessor.process () [private]
Definition at line 21 of file SystemProcessor.java.
References modelManagement.simulink.SystemProcessor.createSystem(), modelManagement.simulink.SystemProcessor.sysRepository, and modelManagement.simulink.SystemProcessor.theSystem.
Referenced by modelManagement.simulink.SystemProcessor.doIt().
Member Data Documentation
HashSet<System> modelManagement.simulink.SystemProcessor.sysRepository = new HashSet<System>() [static, package]
Definition at line 13 of file SystemProcessor.java.
Referenced by modelManagement.simulink.SystemProcessor.process().
System modelManagement.simulink.SystemProcessor.theSystem [package]
Definition at line 12 of file SystemProcessor.java.
Referenced by modelManagement.simulink.SystemProcessor.computeFileName(), modelManagement.simulink.SystemProcessor.computeSimulinkName(), modelManagement.simulink.SystemProcessor.createSystem(), modelManagement.simulink.SystemProcessor.doIt(), and modelManagement.simulink.SystemProcessor.process().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/SystemProcessor.java