Carlota: modelManagement.simulink.PortProcessor Class Reference
modelManagement.simulink.PortProcessor Class Reference
Inherited by modelManagement.simulink.InportsProcessor, and modelManagement.simulink.OutportsProcessor.
Protected Member Functions
void init (System aSystem, SystemLayouter layouter)
void computePosition (Port port)
abstract void addTypeSuffixIfNeeded (Port port)
String getParentName (Port port)
Package Functions
protected< P extends Port >
Collection<?extends
ProtoObject > process (EList< P > ports)
protected< P extends Port > void processPort (P port)
protected< P extends Port > void computeInstanceName (Port port)
Package Attributes
ArrayList< ProtoObject > list = new ArrayList<ProtoObject>()
System theSystem
SystemLayouter layouter
Detailed Description
Definition at line 12 of file PortProcessor.java.
Member Function Documentation
abstract void modelManagement.simulink.PortProcessor.addTypeSuffixIfNeeded (Port port) [protected, pure virtual]
Implemented in modelManagement.simulink.InportsProcessor, and modelManagement.simulink.OutportsProcessor.
Referenced by modelManagement.simulink.PortProcessor.computeInstanceName().
protected<P extends Port> void modelManagement.simulink.PortProcessor.computeInstanceName (Port port) [package]
Definition at line 44 of file PortProcessor.java.
References modelManagement.simulink.PortProcessor.addTypeSuffixIfNeeded(), and modelManagement.simulink.PortProcessor.getParentName().
Referenced by modelManagement.simulink.PortProcessor.processPort().
void modelManagement.simulink.PortProcessor.computePosition (Port port) [protected]
Definition at line 36 of file PortProcessor.java.
References modelManagement.simulink.PortProcessor.layouter, and modelManagement.simulink.SystemLayouter.nextPort().
Referenced by modelManagement.simulink.PortProcessor.processPort().
String modelManagement.simulink.PortProcessor.getParentName (Port port) [protected]
Reimplemented in modelManagement.simulink.InportsProcessor, and modelManagement.simulink.OutportsProcessor.
Definition at line 53 of file PortProcessor.java.
Referenced by modelManagement.simulink.PortProcessor.computeInstanceName().
void modelManagement.simulink.PortProcessor.init (System aSystem, SystemLayouter layouter) [protected]
Definition at line 18 of file PortProcessor.java.
References modelManagement.simulink.PortProcessor.theSystem.
Referenced by modelManagement.simulink.OutportsProcessor.doIt(), and modelManagement.simulink.InportsProcessor.doIt().
protected<P extends Port> Collection<? extends ProtoObject> modelManagement.simulink.PortProcessor.process (EList< P > ports) [package]
Definition at line 23 of file PortProcessor.java.
References modelManagement.simulink.PortProcessor.list, and modelManagement.simulink.PortProcessor.processPort().
Referenced by modelManagement.simulink.OutportsProcessor.doIt(), and modelManagement.simulink.InportsProcessor.doIt().
protected<P extends Port> void modelManagement.simulink.PortProcessor.processPort (P port) [package]
Definition at line 31 of file PortProcessor.java.
References modelManagement.simulink.PortProcessor.computeInstanceName(), and modelManagement.simulink.PortProcessor.computePosition().
Referenced by modelManagement.simulink.PortProcessor.process().
Member Data Documentation
SystemLayouter modelManagement.simulink.PortProcessor.layouter [package]
Definition at line 16 of file PortProcessor.java.
Referenced by modelManagement.simulink.PortProcessor.computePosition().
ArrayList<ProtoObject> modelManagement.simulink.PortProcessor.list = new ArrayList<ProtoObject>() [package]
Definition at line 14 of file PortProcessor.java.
Referenced by modelManagement.simulink.PortProcessor.process().
System modelManagement.simulink.PortProcessor.theSystem [package]
Definition at line 15 of file PortProcessor.java.
Referenced by modelManagement.simulink.PortProcessor.init().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/PortProcessor.java