Carlota: modelManagement.simulink.SimulinkEcoreCreator Class Reference
modelManagement.simulink.SimulinkEcoreCreator Class Reference
Public Member Functions
SimulinkEcoreCreator (SimulinkFactory aFactory)
Model newModel (String modelName)
Model getTopElement ()
System addRootSystem (String name)
System findSystem (String name)
SystemReference addSystem (PropertyList pList)
System addSystem (String name, System parent, String instanceName)
System addSystem (String name, System parent)
Inport addInPort (String name, System parent)
Outport addOutPort (String name, System parent)
Line addLineBetween (String name, System source, System destination, System parent)
Line addLine (String name, Port source, Port destination, System parent)
void addLines (ArrayList< LineInfo > lines) throws PortNotFoundException
System findSystem (UUID uuid)
SystemReference findSystemReference (UUID uuid)
Port findPort (UUID uuid)
Line findLine (UUID uuid)
Static Public Member Functions
static Port findPortWithin (String portName, System aSystem)
static Outport findOutportWithin (String portName, System aSystem)
static Inport findInportWithin (String portName, System aSystem)
Protected Attributes
SimulinkFactory factory
Model theModel
HashMap< String, System > systemRepository
HashMap< UUID, ProtoObject > repository
Private Member Functions
void setUUIDAndAddToRepository (ProtoObject object)
System obtainSystem (String name)
System newSystem (String name)
SystemReference addSystemInstance (String name, System parent, String instanceName)
Static Private Member Functions
static EList< System > createSystemListWithParentAndFirstLevelChldren (System aSystem)
static EList< System > getAllTargets (EList< SystemReference > childrenList)
static Outport findOutportInSystem (String portName, System aSystem)
static Inport findInportInSystem (String portName, System aSystem)
static< IOPortextendsPort > IOPort findPortInList (String portName, EList< IOPort > ports)
Detailed Description
Author:
alesch
Definition at line 29 of file SimulinkEcoreCreator.java.
Constructor & Destructor Documentation
modelManagement.simulink.SimulinkEcoreCreator.SimulinkEcoreCreator (SimulinkFactory aFactory)
Definition at line 36 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.factory, modelManagement.simulink.SimulinkEcoreCreator.repository, and modelManagement.simulink.SimulinkEcoreCreator.systemRepository.
Member Function Documentation
Inport modelManagement.simulink.SimulinkEcoreCreator.addInPort (String name, System parent)
Definition at line 205 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.factory, and modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository().
Referenced by modelManagement.test.SimulinkDemoModelCreator.createF2Subsystems(), modelManagement.test.SimulinkDemoModelCreator.createF2System(), modelManagement.test.SimulinkDemoModelCreator.createF3System(), modelManagement.test.SimulinkEcoreCreatorTest.testAddLines(), modelManagement.test.SimulinkEcoreCreatorTest.testLines(), and modelManagement.test.SimulinkEcoreCreatorTest.testPorts().
Line modelManagement.simulink.SimulinkEcoreCreator.addLine (String name, Port source, Port destination, System parent)
Definition at line 231 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.factory, and modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addLineBetween(), modelManagement.simulink.SimulinkEcoreCreator.addLines(), and modelManagement.test.SimulinkEcoreCreatorTest.testLines().
Line modelManagement.simulink.SimulinkEcoreCreator.addLineBetween (String name, System source, System destination, System parent)
Definition at line 224 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addLine().
Referenced by modelManagement.test.SimulinkDemoModelCreator.createLines().
void modelManagement.simulink.SimulinkEcoreCreator.addLines (ArrayList< LineInfo > lines) throws PortNotFoundException
Definition at line 242 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addLine(), and modelManagement.simulink.SimulinkEcoreCreator.findPort().
Referenced by modelManagement.test.SimulinkEcoreCreatorTest.testAddLines().
Outport modelManagement.simulink.SimulinkEcoreCreator.addOutPort (String name, System parent)
Definition at line 215 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.factory, and modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository().
Referenced by modelManagement.test.SimulinkDemoModelCreator.createF1System(), modelManagement.test.SimulinkDemoModelCreator.createF2Subsystems(), modelManagement.test.SimulinkDemoModelCreator.createF2System(), modelManagement.test.SimulinkDemoModelCreator.createF3System(), modelManagement.test.SimulinkEcoreCreatorTest.testAddLines(), modelManagement.test.SimulinkEcoreCreatorTest.testLines(), and modelManagement.test.SimulinkEcoreCreatorTest.testPorts().
System modelManagement.simulink.SimulinkEcoreCreator.addRootSystem (String name)
Definition at line 63 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.obtainSystem(), modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository(), and modelManagement.simulink.SimulinkEcoreCreator.theModel.
Referenced by modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile(), and modelManagement.test.SimulinkEcoreCreatorTest.testRootSystem().
System modelManagement.simulink.SimulinkEcoreCreator.addSystem (String name, System parent)
Definition at line 200 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addSystem().
System modelManagement.simulink.SimulinkEcoreCreator.addSystem (String name, System parent, String instanceName)
Definition at line 191 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addSystemInstance().
SystemReference modelManagement.simulink.SimulinkEcoreCreator.addSystem (PropertyList pList)
Definition at line 165 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.addSystemInstance(), modelManagement.simulink.PropertyList.getInstanceName(), modelManagement.simulink.PropertyList.getName(), and modelManagement.simulink.PropertyList.getParent().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addSystem(), modelManagement.test.SimulinkDemoModelCreator.createF1System(), modelManagement.test.SimulinkDemoModelCreator.createF2Subsystems(), modelManagement.test.SimulinkDemoModelCreator.createF2System(), modelManagement.test.SimulinkDemoModelCreator.createF3System(), modelManagement.test.SimulinkEcoreCreatorTest.testAddSystemWithPList(), modelManagement.test.SimulinkEcoreCreatorTest.testChild(), modelManagement.test.SimulinkEcoreCreatorTest.testLines(), modelManagement.test.SimulinkEcoreCreatorTest.testReferences(), and modelManagement.test.SimulinkEcoreCreatorTest.testSystemContainment().
SystemReference modelManagement.simulink.SimulinkEcoreCreator.addSystemInstance (String name, System parent, String instanceName) [private]
Definition at line 174 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.factory, modelManagement.simulink.SimulinkEcoreCreator.obtainSystem(), and modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addSystem().
static EList<System> modelManagement.simulink.SimulinkEcoreCreator.createSystemListWithParentAndFirstLevelChldren (System aSystem) [static, private]
Definition at line 128 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.getAllTargets().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.findInportWithin(), and modelManagement.simulink.SimulinkEcoreCreator.findOutportWithin().
static Inport modelManagement.simulink.SimulinkEcoreCreator.findInportInSystem (String portName, System aSystem) [static, private]
Definition at line 150 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.findPortInList().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.findInportWithin().
static Inport modelManagement.simulink.SimulinkEcoreCreator.findInportWithin (String portName, System aSystem) [static]
Definition at line 117 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.createSystemListWithParentAndFirstLevelChldren(), and modelManagement.simulink.SimulinkEcoreCreator.findInportInSystem().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.findPortWithin().
Line modelManagement.simulink.SimulinkEcoreCreator.findLine (UUID uuid)
Definition at line 268 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.repository.
Referenced by modelManagement.test.SimulinkEcoreCreatorTest.testFindInRepository().
static Outport modelManagement.simulink.SimulinkEcoreCreator.findOutportInSystem (String portName, System aSystem) [static, private]
Definition at line 146 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.findPortInList().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.findOutportWithin().
static Outport modelManagement.simulink.SimulinkEcoreCreator.findOutportWithin (String portName, System aSystem) [static]
Definition at line 106 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.createSystemListWithParentAndFirstLevelChldren(), and modelManagement.simulink.SimulinkEcoreCreator.findOutportInSystem().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.findPortWithin().
Port modelManagement.simulink.SimulinkEcoreCreator.findPort (UUID uuid)
Definition at line 264 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.repository.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addLines(), and modelManagement.test.SimulinkEcoreCreatorTest.testFindInRepository().
static <IOPortextendsPort> IOPort modelManagement.simulink.SimulinkEcoreCreator.findPortInList (String portName, EList< IOPort > ports) [static, private]
Definition at line 154 of file SimulinkEcoreCreator.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.findInportInSystem(), and modelManagement.simulink.SimulinkEcoreCreator.findOutportInSystem().
static Port modelManagement.simulink.SimulinkEcoreCreator.findPortWithin (String portName, System aSystem) [static]
Definition at line 98 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.findInportWithin(), and modelManagement.simulink.SimulinkEcoreCreator.findOutportWithin().
System modelManagement.simulink.SimulinkEcoreCreator.findSystem (UUID uuid)
Definition at line 256 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.repository.
System modelManagement.simulink.SimulinkEcoreCreator.findSystem (String name)
Definition at line 94 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.systemRepository.
Referenced by modelManagement.test.SimulinkDemoModelCreator.createF2Subsystems(), modelManagement.test.SimulinkDemoModelCreator.createLines(), modelManagement.simulink.SimulinkEcoreCreator.obtainSystem(), modelManagement.test.SimulinkEcoreCreatorTest.testAddLines(), modelManagement.test.SimulinkEcoreCreatorTest.testFindInRepository(), modelManagement.test.SimulinkEcoreCreatorTest.testFindSystem(), and modelManagement.test.SimulinkEcoreCreatorTest.testReferences().
SystemReference modelManagement.simulink.SimulinkEcoreCreator.findSystemReference (UUID uuid)
Definition at line 260 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.repository.
Referenced by modelManagement.test.SimulinkEcoreCreatorTest.testAddSystemWithPList().
static EList<System> modelManagement.simulink.SimulinkEcoreCreator.getAllTargets (EList< SystemReference > childrenList) [static, private]
Definition at line 137 of file SimulinkEcoreCreator.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.createSystemListWithParentAndFirstLevelChldren().
Model modelManagement.simulink.SimulinkEcoreCreator.getTopElement ()
Definition at line 58 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.theModel.
Referenced by modelManagement.test.SimulinkDemoModelCreator.save(), modelManagement.test.SimulinkEcoreCreatorTest.testNewModel(), and modelManagement.test.SimulinkEcoreCreatorTest.testSystemContainment().
Model modelManagement.simulink.SimulinkEcoreCreator.newModel (String modelName)
Definition at line 43 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.factory, modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository(), and modelManagement.simulink.SimulinkEcoreCreator.theModel.
Referenced by modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile(), and modelManagement.test.SimulinkEcoreCreatorTest.testNewModel().
System modelManagement.simulink.SimulinkEcoreCreator.newSystem (String name) [private]
Definition at line 83 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.factory, modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository(), modelManagement.simulink.SimulinkEcoreCreator.systemRepository, and modelManagement.simulink.SimulinkEcoreCreator.theModel.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.obtainSystem().
System modelManagement.simulink.SimulinkEcoreCreator.obtainSystem (String name) [private]
Definition at line 74 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.findSystem(), and modelManagement.simulink.SimulinkEcoreCreator.newSystem().
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addRootSystem(), and modelManagement.simulink.SimulinkEcoreCreator.addSystemInstance().
void modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository (ProtoObject object) [private]
Definition at line 51 of file SimulinkEcoreCreator.java.
References modelManagement.simulink.SimulinkEcoreCreator.repository.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addInPort(), modelManagement.simulink.SimulinkEcoreCreator.addLine(), modelManagement.simulink.SimulinkEcoreCreator.addOutPort(), modelManagement.simulink.SimulinkEcoreCreator.addRootSystem(), modelManagement.simulink.SimulinkEcoreCreator.addSystemInstance(), modelManagement.simulink.SimulinkEcoreCreator.newModel(), and modelManagement.simulink.SimulinkEcoreCreator.newSystem().
Member Data Documentation
SimulinkFactory modelManagement.simulink.SimulinkEcoreCreator.factory [protected]
Definition at line 31 of file SimulinkEcoreCreator.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addInPort(), modelManagement.simulink.SimulinkEcoreCreator.addLine(), modelManagement.simulink.SimulinkEcoreCreator.addOutPort(), modelManagement.simulink.SimulinkEcoreCreator.addSystemInstance(), modelManagement.simulink.SimulinkEcoreCreator.newModel(), modelManagement.simulink.SimulinkEcoreCreator.newSystem(), and modelManagement.simulink.SimulinkEcoreCreator.SimulinkEcoreCreator().
HashMap<UUID, ProtoObject> modelManagement.simulink.SimulinkEcoreCreator.repository [protected]
Definition at line 34 of file SimulinkEcoreCreator.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.findLine(), modelManagement.simulink.SimulinkEcoreCreator.findPort(), modelManagement.simulink.SimulinkEcoreCreator.findSystem(), modelManagement.simulink.SimulinkEcoreCreator.findSystemReference(), modelManagement.simulink.SimulinkEcoreCreator.setUUIDAndAddToRepository(), and modelManagement.simulink.SimulinkEcoreCreator.SimulinkEcoreCreator().
HashMap<String, System> modelManagement.simulink.SimulinkEcoreCreator.systemRepository [protected]
Definition at line 33 of file SimulinkEcoreCreator.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.findSystem(), modelManagement.simulink.SimulinkEcoreCreator.newSystem(), and modelManagement.simulink.SimulinkEcoreCreator.SimulinkEcoreCreator().
Model modelManagement.simulink.SimulinkEcoreCreator.theModel [protected]
Definition at line 32 of file SimulinkEcoreCreator.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addRootSystem(), modelManagement.simulink.SimulinkEcoreCreator.getTopElement(), modelManagement.simulink.SimulinkEcoreCreator.newModel(), and modelManagement.simulink.SimulinkEcoreCreator.newSystem().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/SimulinkEcoreCreator.java