Carlota: modelManagement.ModelValidator Class Reference
modelManagement.ModelValidator Class Reference
Public Member Functions
ModelValidator (Resource resource)
void doIt () throws InvalidModelException
Package Attributes
Resource resource
Hashtable< EObject, String > invalidObjects
StringBuffer strBuffer
Private Member Functions
void validateEachElement ()
void addToListIfInvalid (EObject eObject)
Boolean validateEObject (EObject eObject)
void resetStringBuffer ()
void printDiagnostic (Diagnostic diagnostic, String indent)
void recordIndentedMessage (String message, String indent)
Detailed Description
Definition at line 12 of file ModelValidator.java.
Constructor & Destructor Documentation
modelManagement.ModelValidator.ModelValidator (Resource resource)
Definition at line 18 of file ModelValidator.java.
References modelManagement.ModelValidator.invalidObjects.
Member Function Documentation
void modelManagement.ModelValidator.addToListIfInvalid (EObject eObject) [private]
Definition at line 40 of file ModelValidator.java.
References modelManagement.ModelValidator.invalidObjects, modelManagement.ModelValidator.strBuffer, and modelManagement.ModelValidator.validateEObject().
Referenced by modelManagement.ModelValidator.validateEachElement().
void modelManagement.ModelValidator.doIt () throws InvalidModelException
Definition at line 23 of file ModelValidator.java.
References modelManagement.ModelValidator.invalidObjects, and modelManagement.ModelValidator.validateEachElement().
Referenced by modelManagement.ModelManager.validateIt().
void modelManagement.ModelValidator.printDiagnostic (Diagnostic diagnostic, String indent) [private]
Definition at line 61 of file ModelValidator.java.
References modelManagement.ModelValidator.recordIndentedMessage().
Referenced by modelManagement.ModelValidator.validateEObject().
void modelManagement.ModelValidator.recordIndentedMessage (String message, String indent) [private]
Parameters:
message
indent
Definition at line 73 of file ModelValidator.java.
References modelManagement.ModelValidator.strBuffer.
Referenced by modelManagement.ModelValidator.printDiagnostic().
void modelManagement.ModelValidator.resetStringBuffer () [private]
Definition at line 56 of file ModelValidator.java.
References modelManagement.ModelValidator.strBuffer.
Referenced by modelManagement.ModelValidator.validateEObject().
void modelManagement.ModelValidator.validateEachElement () [private]
Definition at line 34 of file ModelValidator.java.
References modelManagement.ModelValidator.addToListIfInvalid(), and modelManagement.ModelValidator.resource.
Referenced by modelManagement.ModelValidator.doIt().
Boolean modelManagement.ModelValidator.validateEObject (EObject eObject) [private]
Definition at line 46 of file ModelValidator.java.
References modelManagement.ModelValidator.printDiagnostic(), and modelManagement.ModelValidator.resetStringBuffer().
Referenced by modelManagement.ModelValidator.addToListIfInvalid().
Member Data Documentation
Hashtable<EObject, String> modelManagement.ModelValidator.invalidObjects [package]
Definition at line 15 of file ModelValidator.java.
Referenced by modelManagement.ModelValidator.addToListIfInvalid(), modelManagement.ModelValidator.doIt(), and modelManagement.ModelValidator.ModelValidator().
Resource modelManagement.ModelValidator.resource [package]
Definition at line 14 of file ModelValidator.java.
Referenced by modelManagement.ModelValidator.validateEachElement().
StringBuffer modelManagement.ModelValidator.strBuffer [package]
Definition at line 16 of file ModelValidator.java.
Referenced by modelManagement.ModelValidator.addToListIfInvalid(), modelManagement.ModelValidator.recordIndentedMessage(), and modelManagement.ModelValidator.resetStringBuffer().
The documentation for this class was generated from the following file:
src/modelManagement/ModelValidator.java