Carlota: modelManagement.simulink.OutportsProcessor Class Reference
modelManagement.simulink.OutportsProcessor Class Reference
Inherits modelManagement::simulink::PortProcessor.
Public Member Functions
String getParentName (Port port)
Static Public Member Functions
static Collection<?extends
ProtoObject > doIt (System aSystem, SystemLayouter layouter)
Protected Member Functions
void addTypeSuffixIfNeeded (Port port)
Detailed Description
Definition at line 10 of file OutportsProcessor.java.
Member Function Documentation
void modelManagement.simulink.OutportsProcessor.addTypeSuffixIfNeeded (Port port) [protected, virtual]
Implements modelManagement.simulink.PortProcessor.
Definition at line 28 of file OutportsProcessor.java.
static Collection<? extends ProtoObject> modelManagement.simulink.OutportsProcessor.doIt (System aSystem, SystemLayouter layouter) [static]
Definition at line 12 of file OutportsProcessor.java.
References modelManagement.simulink.PortProcessor.init(), modelManagement.simulink.PortProcessor.process(), and modelManagement.simulink.SystemLayouter.startWithOutports().
String modelManagement.simulink.OutportsProcessor.getParentName (Port port)
Reimplemented from modelManagement.simulink.PortProcessor.
Definition at line 22 of file OutportsProcessor.java.
The documentation for this class was generated from the following file:
src/modelManagement/simulink/OutportsProcessor.java