Carlota: modelManagement.simulink.SimulinkModelManager Class Reference
modelManagement.simulink.SimulinkModelManager Class Reference
Inherits modelManagement::ModelManager.
Public Member Functions
SimulinkFactory getFactory ()
SimulinkModelManager ()
SimulinkModelManager (String modelPath)
SimulinkModelManager (URI model)
Protected Member Functions
void initMetaModel ()
Detailed Description
Definition at line 15 of file SimulinkModelManager.java.
Constructor & Destructor Documentation
modelManagement.simulink.SimulinkModelManager.SimulinkModelManager ()
Definition at line 33 of file SimulinkModelManager.java.
modelManagement.simulink.SimulinkModelManager.SimulinkModelManager (String modelPath)
Definition at line 37 of file SimulinkModelManager.java.
modelManagement.simulink.SimulinkModelManager.SimulinkModelManager (URI model)
Definition at line 41 of file SimulinkModelManager.java.
References modelManagement.ModelManager.init(), and modelManagement.ModelManager.setFileExtension().
Member Function Documentation
SimulinkFactory modelManagement.simulink.SimulinkModelManager.getFactory ()
Reimplemented from modelManagement.ModelManager.
Definition at line 26 of file SimulinkModelManager.java.
Referenced by modelManagement.test.SimulinkDemoModelCreator.getNewModelAndNewFile(), modelManagement.test.SimulinkModelManagerTest.testNewModel(), and modelManagement.test.SimulinkEcoreCreatorTest.testSimulinkEcoreCreator().
void modelManagement.simulink.SimulinkModelManager.initMetaModel () [protected, virtual]
Implements modelManagement.ModelManager.
Definition at line 21 of file SimulinkModelManager.java.
References modelManagement.ModelManager.ePackage.
The documentation for this class was generated from the following file:
src/modelManagement/simulink/SimulinkModelManager.java