Carlota: modelManagement.simulink.PropertyList Class Reference
modelManagement.simulink.PropertyList Class Reference
Inherits java::util::HashMap< String, Object >.
Public Member Functions
PropertyList (String name, System parent, String instanceName)
String getPosition ()
String getName ()
String getInstanceName ()
System getParent ()
Detailed Description
Definition at line 8 of file PropertyList.java.
Constructor & Destructor Documentation
modelManagement.simulink.PropertyList.PropertyList (String name, System parent, String instanceName)
Definition at line 10 of file PropertyList.java.
Member Function Documentation
String modelManagement.simulink.PropertyList.getInstanceName ()
Definition at line 28 of file PropertyList.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addSystem().
String modelManagement.simulink.PropertyList.getName ()
Definition at line 24 of file PropertyList.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addSystem().
System modelManagement.simulink.PropertyList.getParent ()
Definition at line 32 of file PropertyList.java.
Referenced by modelManagement.simulink.SimulinkEcoreCreator.addSystem().
String modelManagement.simulink.PropertyList.getPosition ()
Definition at line 20 of file PropertyList.java.
The documentation for this class was generated from the following file:
src/modelManagement/simulink/PropertyList.java