Carlota: modelManagement.simulink.ListOrganizer Class Reference
modelManagement.simulink.ListOrganizer Class Reference
Static Public Member Functions
static ArrayList< ProtoObject > reorder (ArrayList< ProtoObject > allElements)
Package Attributes
ArrayList< ProtoObject > reorderedElements = new ArrayList<ProtoObject>()
ArrayList< ProtoObject > originalList
int systemStart
int systemEnd
Private Member Functions
ListOrganizer (ArrayList< ProtoObject > allElements)
ArrayList< ProtoObject > doIt ()
void displayReorderedElements ()
void addTheModelElement ()
void findAllSystems ()
boolean findNextSystemBackwards ()
boolean findEndOfSystem (int start)
boolean findNextSystemStart (List< ProtoObject > subList)
Detailed Description
Definition at line 9 of file ListOrganizer.java.
Constructor & Destructor Documentation
modelManagement.simulink.ListOrganizer.ListOrganizer (ArrayList< ProtoObject > allElements) [private]
Definition at line 16 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.originalList, modelManagement.simulink.ListOrganizer.systemEnd, and modelManagement.simulink.ListOrganizer.systemStart.
Referenced by modelManagement.simulink.ListOrganizer.reorder().
Member Function Documentation
void modelManagement.simulink.ListOrganizer.addTheModelElement () [private]
Definition at line 53 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.originalList, and modelManagement.simulink.ListOrganizer.reorderedElements.
Referenced by modelManagement.simulink.ListOrganizer.doIt().
void modelManagement.simulink.ListOrganizer.displayReorderedElements () [private]
Definition at line 43 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.reorderedElements.
Referenced by modelManagement.simulink.ListOrganizer.doIt().
ArrayList<ProtoObject> modelManagement.simulink.ListOrganizer.doIt () [private]
Definition at line 31 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.addTheModelElement(), modelManagement.simulink.ListOrganizer.displayReorderedElements(), modelManagement.simulink.ListOrganizer.findAllSystems(), and modelManagement.simulink.ListOrganizer.reorderedElements.
Referenced by modelManagement.simulink.ListOrganizer.reorder().
void modelManagement.simulink.ListOrganizer.findAllSystems () [private]
Definition at line 81 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.findNextSystemBackwards(), modelManagement.simulink.ListOrganizer.originalList, modelManagement.simulink.ListOrganizer.reorderedElements, modelManagement.simulink.ListOrganizer.systemEnd, and modelManagement.simulink.ListOrganizer.systemStart.
Referenced by modelManagement.simulink.ListOrganizer.doIt().
boolean modelManagement.simulink.ListOrganizer.findEndOfSystem (int start) [private]
Definition at line 97 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.originalList, and modelManagement.simulink.ListOrganizer.systemEnd.
Referenced by modelManagement.simulink.ListOrganizer.findNextSystemBackwards().
boolean modelManagement.simulink.ListOrganizer.findNextSystemBackwards () [private]
Definition at line 89 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.findEndOfSystem(), modelManagement.simulink.ListOrganizer.findNextSystemStart(), modelManagement.simulink.ListOrganizer.originalList, and modelManagement.simulink.ListOrganizer.systemStart.
Referenced by modelManagement.simulink.ListOrganizer.findAllSystems().
boolean modelManagement.simulink.ListOrganizer.findNextSystemStart (List< ProtoObject > subList) [private]
Definition at line 118 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.systemStart.
Referenced by modelManagement.simulink.ListOrganizer.findNextSystemBackwards().
static ArrayList<ProtoObject> modelManagement.simulink.ListOrganizer.reorder (ArrayList< ProtoObject > allElements) [static]
Definition at line 23 of file ListOrganizer.java.
References modelManagement.simulink.ListOrganizer.doIt(), and modelManagement.simulink.ListOrganizer.ListOrganizer().
Member Data Documentation
ArrayList<ProtoObject> modelManagement.simulink.ListOrganizer.originalList [package]
Definition at line 11 of file ListOrganizer.java.
Referenced by modelManagement.simulink.ListOrganizer.addTheModelElement(), modelManagement.simulink.ListOrganizer.findAllSystems(), modelManagement.simulink.ListOrganizer.findEndOfSystem(), modelManagement.simulink.ListOrganizer.findNextSystemBackwards(), and modelManagement.simulink.ListOrganizer.ListOrganizer().
ArrayList<ProtoObject> modelManagement.simulink.ListOrganizer.reorderedElements = new ArrayList<ProtoObject>() [package]
Definition at line 10 of file ListOrganizer.java.
Referenced by modelManagement.simulink.ListOrganizer.addTheModelElement(), modelManagement.simulink.ListOrganizer.displayReorderedElements(), modelManagement.simulink.ListOrganizer.doIt(), and modelManagement.simulink.ListOrganizer.findAllSystems().
int modelManagement.simulink.ListOrganizer.systemEnd [package]
Definition at line 14 of file ListOrganizer.java.
Referenced by modelManagement.simulink.ListOrganizer.findAllSystems(), modelManagement.simulink.ListOrganizer.findEndOfSystem(), and modelManagement.simulink.ListOrganizer.ListOrganizer().
int modelManagement.simulink.ListOrganizer.systemStart [package]
Definition at line 13 of file ListOrganizer.java.
Referenced by modelManagement.simulink.ListOrganizer.findAllSystems(), modelManagement.simulink.ListOrganizer.findNextSystemBackwards(), modelManagement.simulink.ListOrganizer.findNextSystemStart(), and modelManagement.simulink.ListOrganizer.ListOrganizer().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/ListOrganizer.java