Carlota: modelManagement.simulink.SysRefsProcessor Class Reference
modelManagement.simulink.SysRefsProcessor Class Reference
Static Public Member Functions
static Collection<?extends
ProtoObject > doIt (System aSystem, SystemLayouter layouter)
Package Attributes
ArrayList< ProtoObject > list = new ArrayList<ProtoObject>()
System theSystem
SystemLayouter layouter
Private Member Functions
Collection<?extends ProtoObject > process ()
void processSystemReference (SystemReference sysRef)
void computePosition (SystemReference sysRef)
void computeInstanceName (SystemReference sysRef)
Detailed Description
Definition at line 10 of file SysRefsProcessor.java.
Member Function Documentation
void modelManagement.simulink.SysRefsProcessor.computeInstanceName (SystemReference sysRef) [private]
Definition at line 53 of file SysRefsProcessor.java.
Referenced by modelManagement.simulink.SysRefsProcessor.processSystemReference().
void modelManagement.simulink.SysRefsProcessor.computePosition (SystemReference sysRef) [private]
Definition at line 44 of file SysRefsProcessor.java.
References modelManagement.simulink.SysRefsProcessor.layouter, and modelManagement.simulink.SystemLayouter.nextSystem().
Referenced by modelManagement.simulink.SysRefsProcessor.processSystemReference().
static Collection<? extends ProtoObject> modelManagement.simulink.SysRefsProcessor.doIt (System aSystem, SystemLayouter layouter) [static]
Definition at line 16 of file SysRefsProcessor.java.
References modelManagement.simulink.SysRefsProcessor.layouter, modelManagement.simulink.SysRefsProcessor.process(), and modelManagement.simulink.SysRefsProcessor.theSystem.
Collection<? extends ProtoObject> modelManagement.simulink.SysRefsProcessor.process () [private]
Definition at line 27 of file SysRefsProcessor.java.
References modelManagement.simulink.SysRefsProcessor.layouter, modelManagement.simulink.SysRefsProcessor.list, modelManagement.simulink.SysRefsProcessor.processSystemReference(), modelManagement.simulink.SystemLayouter.startWithSystems(), and modelManagement.simulink.SysRefsProcessor.theSystem.
Referenced by modelManagement.simulink.SysRefsProcessor.doIt().
void modelManagement.simulink.SysRefsProcessor.processSystemReference (SystemReference sysRef) [private]
Definition at line 36 of file SysRefsProcessor.java.
References modelManagement.simulink.SysRefsProcessor.computeInstanceName(), modelManagement.simulink.SysRefsProcessor.computePosition(), and modelManagement.simulink.SysRefsProcessor.list.
Referenced by modelManagement.simulink.SysRefsProcessor.process().
Member Data Documentation
SystemLayouter modelManagement.simulink.SysRefsProcessor.layouter [package]
Definition at line 14 of file SysRefsProcessor.java.
Referenced by modelManagement.simulink.SysRefsProcessor.computePosition(), modelManagement.simulink.SysRefsProcessor.doIt(), and modelManagement.simulink.SysRefsProcessor.process().
ArrayList<ProtoObject> modelManagement.simulink.SysRefsProcessor.list = new ArrayList<ProtoObject>() [package]
Definition at line 12 of file SysRefsProcessor.java.
Referenced by modelManagement.simulink.SysRefsProcessor.process(), and modelManagement.simulink.SysRefsProcessor.processSystemReference().
System modelManagement.simulink.SysRefsProcessor.theSystem [package]
Definition at line 13 of file SysRefsProcessor.java.
Referenced by modelManagement.simulink.SysRefsProcessor.doIt(), and modelManagement.simulink.SysRefsProcessor.process().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/SysRefsProcessor.java