Carlota: modelManagement.simulink.LineInfo Class Reference
modelManagement.simulink.LineInfo Class Reference
Public Member Functions
LineInfo (System lineParent)
void setName (String name)
String getName ()
System getLineParent ()
void setSrcPort (String uuidStr)
void setSrcPort (UUID srcPort)
UUID getSrcPort ()
void setDstPort (String uuidStr)
void setDstPort (UUID dstPort)
UUID getDstPort ()
Static Public Member Functions
static ArrayList< LineInfo > createArray ()
Public Attributes
String lineName
UUID srcPort
UUID dstPort
System lineParent
Detailed Description
Definition at line 8 of file LineInfo.java.
Constructor & Destructor Documentation
modelManagement.simulink.LineInfo.LineInfo (System lineParent)
Definition at line 17 of file LineInfo.java.
Member Function Documentation
static ArrayList<LineInfo> modelManagement.simulink.LineInfo.createArray () [static]
Definition at line 33 of file LineInfo.java.
UUID modelManagement.simulink.LineInfo.getDstPort ()
Definition at line 61 of file LineInfo.java.
References modelManagement.simulink.LineInfo.dstPort.
System modelManagement.simulink.LineInfo.getLineParent ()
Definition at line 37 of file LineInfo.java.
References modelManagement.simulink.LineInfo.lineParent.
String modelManagement.simulink.LineInfo.getName ()
Definition at line 25 of file LineInfo.java.
References modelManagement.simulink.LineInfo.lineName.
UUID modelManagement.simulink.LineInfo.getSrcPort ()
Definition at line 49 of file LineInfo.java.
References modelManagement.simulink.LineInfo.srcPort.
void modelManagement.simulink.LineInfo.setDstPort (UUID dstPort)
Definition at line 57 of file LineInfo.java.
void modelManagement.simulink.LineInfo.setDstPort (String uuidStr)
Definition at line 53 of file LineInfo.java.
Referenced by modelManagement.test.SimulinkEcoreCreatorTest.testAddLines().
void modelManagement.simulink.LineInfo.setName (String name)
Definition at line 21 of file LineInfo.java.
References modelManagement.simulink.LineInfo.lineName.
Referenced by modelManagement.test.SimulinkEcoreCreatorTest.testAddLines().
void modelManagement.simulink.LineInfo.setSrcPort (UUID srcPort)
Definition at line 45 of file LineInfo.java.
void modelManagement.simulink.LineInfo.setSrcPort (String uuidStr)
Definition at line 41 of file LineInfo.java.
Referenced by modelManagement.test.SimulinkEcoreCreatorTest.testAddLines().
Member Data Documentation
UUID modelManagement.simulink.LineInfo.dstPort
Definition at line 12 of file LineInfo.java.
Referenced by modelManagement.simulink.LineInfo.getDstPort().
String modelManagement.simulink.LineInfo.lineName
Definition at line 10 of file LineInfo.java.
Referenced by modelManagement.simulink.LineInfo.getName(), and modelManagement.simulink.LineInfo.setName().
System modelManagement.simulink.LineInfo.lineParent
Definition at line 13 of file LineInfo.java.
Referenced by modelManagement.simulink.LineInfo.getLineParent().
UUID modelManagement.simulink.LineInfo.srcPort
Definition at line 11 of file LineInfo.java.
Referenced by modelManagement.simulink.LineInfo.getSrcPort().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/LineInfo.java