Carlota: modelManagement.ModelManager Class Reference
modelManagement.ModelManager Class Reference
Resumen corto äcä.
Inherited by modelManagement.east.EastModelManager, and modelManagement.simulink.SimulinkModelManager.
Public Member Functions
ModelManager ()
Brief desc ends here.
ModelManager (String modelPath)
ModelManager (URI model)
void loadIt () throws InvalidModelException
void saveIt () throws IOException
void saveAs (String pathname) throws IOException
void saveAs (URI modelURI) throws IOException
void saveAsWithPropperExtension (String originalPathName) throws IOException
String replaceExtension (String pathName, String extension)
void validateIt () throws InvalidModelException
EObject getTopElement ()
void setTopElement (EObject topElement)
String getNsURI ()
EFactory getFactory ()
String getFileExtension ()
Protected Member Functions
abstract void initMetaModel ()
void init (URI model)
void setFileExtension (String fileExtension)
Protected Attributes
URI model
Resource resource
ResourceSet resourceSet = new ResourceSetImpl()
EPackage ePackage = null
String fileExtension = Resource.Factory.Registry.DEFAULT_EXTENSION
Private Member Functions
void setTopElementIn (Resource aResource)
void setTopElementIn (EObject topElement, Resource aResource)
Resource createNewResource (URI modelURI)
void setResourceFactoryForFileExtension (String extension)
Register the appropriate resource factory to handle file extensions.
Detailed Description
Resumen corto äcä.
This class can read from file, validate, and write to file ecore models. It can be used in Java standalone mode, as it first registers the metamodel. In order to write models, subclasses should define initMetaModel method.
Author:
Alex Schenkman
Definition at line 26 of file ModelManager.java.
Constructor & Destructor Documentation
modelManagement.ModelManager.ModelManager ()
Brief desc ends here.
The rest is the detailed description. or Am i wrong?
Definition at line 41 of file ModelManager.java.
modelManagement.ModelManager.ModelManager (String modelPath)
Parameters:
modelPath File path to a model file.
Definition at line 48 of file ModelManager.java.
modelManagement.ModelManager.ModelManager (URI model)
Definition at line 52 of file ModelManager.java.
References modelManagement.ModelManager.init().
Member Function Documentation
Resource modelManagement.ModelManager.createNewResource (URI modelURI) [private]
Definition at line 116 of file ModelManager.java.
References modelManagement.ModelManager.resourceSet.
Referenced by modelManagement.ModelManager.saveAs(), and modelManagement.ModelManager.setTopElement().
EFactory modelManagement.ModelManager.getFactory ()
Reimplemented in modelManagement.east.EastModelManager, and modelManagement.simulink.SimulinkModelManager.
Definition at line 124 of file ModelManager.java.
References modelManagement.ModelManager.ePackage.
String modelManagement.ModelManager.getFileExtension ()
Definition at line 145 of file ModelManager.java.
References modelManagement.ModelManager.fileExtension.
String modelManagement.ModelManager.getNsURI ()
Definition at line 120 of file ModelManager.java.
References modelManagement.ModelManager.ePackage.
EObject modelManagement.ModelManager.getTopElement ()
Definition at line 103 of file ModelManager.java.
References modelManagement.ModelManager.resource.
Referenced by modelManagement.test.Test.main(), modelManagement.ModelManager.saveIt(), modelManagement.ModelManager.setTopElementIn(), modelManagement.test.ModelProcessorTest.testModelCreator(), and modelManagement.test.SimulinkModelManagerTest.testNewModel().
void modelManagement.ModelManager.init (URI model) [protected]
Definition at line 139 of file ModelManager.java.
References modelManagement.ModelManager.fileExtension, modelManagement.ModelManager.initMetaModel(), and modelManagement.ModelManager.setResourceFactoryForFileExtension().
Referenced by modelManagement.east.EastModelManager.EastModelManager(), modelManagement.ModelManager.ModelManager(), and modelManagement.simulink.SimulinkModelManager.SimulinkModelManager().
abstract void modelManagement.ModelManager.initMetaModel () [protected, pure virtual]
Implemented in modelManagement.east.EastModelManager, and modelManagement.simulink.SimulinkModelManager.
Referenced by modelManagement.ModelManager.init().
void modelManagement.ModelManager.loadIt () throws InvalidModelException
Definition at line 56 of file ModelManager.java.
References modelManagement.ModelManager.model, modelManagement.ModelManager.resource, and modelManagement.ModelManager.resourceSet.
Referenced by modelManagement.test.Test.main(), modelManagement.test.ModelProcessorTest.testModelCreator(), modelManagement.test.SimulinkModelManagerTest.testNewModel(), and modelManagement.test.EastModelManagerTest.testValid().
String modelManagement.ModelManager.replaceExtension (String pathName, String extension)
Definition at line 85 of file ModelManager.java.
Referenced by modelManagement.ModelManager.saveAsWithPropperExtension(), and modelManagement.test.SimulinkModelManagerTest.testReplacExtension().
void modelManagement.ModelManager.saveAs (URI modelURI) throws IOException
Definition at line 73 of file ModelManager.java.
References modelManagement.ModelManager.createNewResource(), and modelManagement.ModelManager.setTopElementIn().
void modelManagement.ModelManager.saveAs (String pathname) throws IOException
Definition at line 68 of file ModelManager.java.
Referenced by modelManagement.ModelManager.saveAsWithPropperExtension(), and modelManagement.ModelManager.saveIt().
void modelManagement.ModelManager.saveAsWithPropperExtension (String originalPathName) throws IOException
Definition at line 79 of file ModelManager.java.
References modelManagement.ModelManager.fileExtension, modelManagement.ModelManager.replaceExtension(), and modelManagement.ModelManager.saveAs().
void modelManagement.ModelManager.saveIt () throws IOException
Definition at line 60 of file ModelManager.java.
References modelManagement.ModelManager.getTopElement(), modelManagement.ModelManager.model, modelManagement.ModelManager.resource, and modelManagement.ModelManager.saveAs().
Referenced by modelManagement.test.SimulinkDemoModelCreator.save(), and modelManagement.test.SimulinkModelManagerTest.testNewModel().
void modelManagement.ModelManager.setFileExtension (String fileExtension) [protected]
Definition at line 149 of file ModelManager.java.
Referenced by modelManagement.east.EastModelManager.EastModelManager(), and modelManagement.simulink.SimulinkModelManager.SimulinkModelManager().
void modelManagement.ModelManager.setResourceFactoryForFileExtension (String extension) [private]
Register the appropriate resource factory to handle file extensions.
In this case, all files (*) will handled by XMI resource Factory.
Definition at line 132 of file ModelManager.java.
References modelManagement.ModelManager.resourceSet.
Referenced by modelManagement.ModelManager.init().
void modelManagement.ModelManager.setTopElement (EObject topElement)
Definition at line 109 of file ModelManager.java.
References modelManagement.ModelManager.createNewResource(), modelManagement.ModelManager.model, modelManagement.ModelManager.resource, and modelManagement.ModelManager.setTopElementIn().
Referenced by modelManagement.test.SimulinkDemoModelCreator.save(), and modelManagement.test.SimulinkModelManagerTest.testNewModel().
void modelManagement.ModelManager.setTopElementIn (EObject topElement, Resource aResource) [private]
Definition at line 93 of file ModelManager.java.
void modelManagement.ModelManager.setTopElementIn (Resource aResource) [private]
Definition at line 89 of file ModelManager.java.
References modelManagement.ModelManager.getTopElement().
Referenced by modelManagement.ModelManager.saveAs(), and modelManagement.ModelManager.setTopElement().
void modelManagement.ModelManager.validateIt () throws InvalidModelException
Definition at line 97 of file ModelManager.java.
References modelManagement.ModelValidator.doIt(), and modelManagement.ModelManager.resource.
Referenced by modelManagement.test.SimulinkDemoModelCreator.save(), modelManagement.test.ModelProcessorTest.testModelCreator(), and modelManagement.test.EastModelManagerTest.testValid().
Member Data Documentation
EPackage modelManagement.ModelManager.ePackage = null [protected]
Definition at line 31 of file ModelManager.java.
Referenced by modelManagement.ModelManager.getFactory(), modelManagement.ModelManager.getNsURI(), modelManagement.simulink.SimulinkModelManager.initMetaModel(), and modelManagement.east.EastModelManager.initMetaModel().
String modelManagement.ModelManager.fileExtension = Resource.Factory.Registry.DEFAULT_EXTENSION [protected]
Definition at line 32 of file ModelManager.java.
Referenced by modelManagement.ModelManager.getFileExtension(), modelManagement.ModelManager.init(), and modelManagement.ModelManager.saveAsWithPropperExtension().
URI modelManagement.ModelManager.model [protected]
Definition at line 28 of file ModelManager.java.
Referenced by modelManagement.ModelManager.loadIt(), modelManagement.ModelManager.saveIt(), and modelManagement.ModelManager.setTopElement().
Resource modelManagement.ModelManager.resource [protected]
Definition at line 29 of file ModelManager.java.
Referenced by modelManagement.ModelManager.getTopElement(), modelManagement.ModelManager.loadIt(), modelManagement.ModelManager.saveIt(), modelManagement.ModelManager.setTopElement(), and modelManagement.ModelManager.validateIt().
ResourceSet modelManagement.ModelManager.resourceSet = new ResourceSetImpl() [protected]
Definition at line 30 of file ModelManager.java.
Referenced by modelManagement.ModelManager.createNewResource(), modelManagement.ModelManager.loadIt(), and modelManagement.ModelManager.setResourceFactoryForFileExtension().
The documentation for this class was generated from the following file:
src/modelManagement/ModelManager.java