Carlota: modelManagement.simulink.ModelProcessor Class Reference
modelManagement.simulink.ModelProcessor Class Reference
Static Public Member Functions
static ArrayList< ProtoObject > doIt (Model aModel)
Package Attributes
Model theModel
ArrayList< ProtoObject > allElements = new ArrayList<ProtoObject>()
Private Member Functions
ArrayList< ProtoObject > process ()
void computeSimulinkName ()
Detailed Description
Definition at line 8 of file ModelProcessor.java.
Member Function Documentation
void modelManagement.simulink.ModelProcessor.computeSimulinkName () [private]
Definition at line 31 of file ModelProcessor.java.
References modelManagement.simulink.ModelProcessor.theModel.
Referenced by modelManagement.simulink.ModelProcessor.process().
static ArrayList<ProtoObject> modelManagement.simulink.ModelProcessor.doIt (Model aModel) [static]
Definition at line 13 of file ModelProcessor.java.
References modelManagement.simulink.ModelProcessor.process(), and modelManagement.simulink.ModelProcessor.theModel.
ArrayList<ProtoObject> modelManagement.simulink.ModelProcessor.process () [private]
Definition at line 20 of file ModelProcessor.java.
References modelManagement.simulink.ModelProcessor.allElements, modelManagement.simulink.ModelProcessor.computeSimulinkName(), and modelManagement.simulink.ModelProcessor.theModel.
Referenced by modelManagement.simulink.ModelProcessor.doIt().
Member Data Documentation
ArrayList<ProtoObject> modelManagement.simulink.ModelProcessor.allElements = new ArrayList<ProtoObject>() [package]
Definition at line 11 of file ModelProcessor.java.
Referenced by modelManagement.simulink.ModelProcessor.process().
Model modelManagement.simulink.ModelProcessor.theModel [package]
Definition at line 10 of file ModelProcessor.java.
Referenced by modelManagement.simulink.ModelProcessor.computeSimulinkName(), modelManagement.simulink.ModelProcessor.doIt(), and modelManagement.simulink.ModelProcessor.process().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/ModelProcessor.java