Carlota: modelManagement.test.ModelProcessorTest Class Reference
modelManagement.test.ModelProcessorTest Class Reference
Public Member Functions
void testModelCreator () throws InvalidModelException
Package Attributes
ModelProcessor modelProcessor = new ModelProcessor()
Detailed Description
Definition at line 17 of file ModelProcessorTest.java.
Member Function Documentation
void modelManagement.test.ModelProcessorTest.testModelCreator () throws InvalidModelException
Definition at line 22 of file ModelProcessorTest.java.
References modelManagement.ModelManager.getTopElement(), modelManagement.ModelManager.loadIt(), and modelManagement.ModelManager.validateIt().
Member Data Documentation
ModelProcessor modelManagement.test.ModelProcessorTest.modelProcessor = new ModelProcessor() [package]
Definition at line 19 of file ModelProcessorTest.java.
The documentation for this class was generated from the following file:
src/modelManagement/test/ModelProcessorTest.java