Carlota: modelManagement.simulink.SystemLayouter Class Reference
modelManagement.simulink.SystemLayouter Class Reference
Public Member Functions
void startWithSystems ()
void startWithOutports ()
String nextPort ()
String nextSystem ()
void testBuildPositionString ()
Package Attributes
final Integer distanceBetweenPorts = new Integer(60)
final Integer distanceBetweenSystmes = new Integer(90)
final Integer blockSizeHoriz = new Integer(250)
final Integer blockSizeVert = new Integer(100)
final Integer portSizeHoriz = new Integer(30)
final Integer portSizeVert = new Integer(14)
Private Member Functions
String buildPositionString ()
Private Attributes
Integer top = new Integer(40)
Integer left = new Integer(35)
Integer bottom = new Integer(0)
Integer right = new Integer(0)
Detailed Description
Definition at line 6 of file SystemLayouter.java.
Member Function Documentation
String modelManagement.simulink.SystemLayouter.buildPositionString () [private]
Definition at line 47 of file SystemLayouter.java.
References modelManagement.simulink.SystemLayouter.bottom, modelManagement.simulink.SystemLayouter.left, modelManagement.simulink.SystemLayouter.right, and modelManagement.simulink.SystemLayouter.top.
Referenced by modelManagement.simulink.SystemLayouter.nextPort(), modelManagement.simulink.SystemLayouter.nextSystem(), and modelManagement.simulink.SystemLayouter.testBuildPositionString().
String modelManagement.simulink.SystemLayouter.nextPort ()
Definition at line 31 of file SystemLayouter.java.
References modelManagement.simulink.SystemLayouter.bottom, modelManagement.simulink.SystemLayouter.buildPositionString(), modelManagement.simulink.SystemLayouter.distanceBetweenPorts, modelManagement.simulink.SystemLayouter.left, modelManagement.simulink.SystemLayouter.portSizeHoriz, modelManagement.simulink.SystemLayouter.portSizeVert, modelManagement.simulink.SystemLayouter.right, and modelManagement.simulink.SystemLayouter.top.
Referenced by modelManagement.simulink.PortProcessor.computePosition().
String modelManagement.simulink.SystemLayouter.nextSystem ()
Definition at line 39 of file SystemLayouter.java.
References modelManagement.simulink.SystemLayouter.blockSizeHoriz, modelManagement.simulink.SystemLayouter.blockSizeVert, modelManagement.simulink.SystemLayouter.bottom, modelManagement.simulink.SystemLayouter.buildPositionString(), modelManagement.simulink.SystemLayouter.distanceBetweenSystmes, modelManagement.simulink.SystemLayouter.left, modelManagement.simulink.SystemLayouter.right, and modelManagement.simulink.SystemLayouter.top.
Referenced by modelManagement.simulink.SysRefsProcessor.computePosition().
void modelManagement.simulink.SystemLayouter.startWithOutports ()
Definition at line 25 of file SystemLayouter.java.
References modelManagement.simulink.SystemLayouter.blockSizeHoriz, modelManagement.simulink.SystemLayouter.distanceBetweenSystmes, modelManagement.simulink.SystemLayouter.left, and modelManagement.simulink.SystemLayouter.top.
Referenced by modelManagement.simulink.OutportsProcessor.doIt().
void modelManagement.simulink.SystemLayouter.startWithSystems ()
Definition at line 20 of file SystemLayouter.java.
References modelManagement.simulink.SystemLayouter.left, and modelManagement.simulink.SystemLayouter.top.
Referenced by modelManagement.simulink.SysRefsProcessor.process().
void modelManagement.simulink.SystemLayouter.testBuildPositionString ()
Definition at line 54 of file SystemLayouter.java.
References modelManagement.simulink.SystemLayouter.buildPositionString().
Member Data Documentation
final Integer modelManagement.simulink.SystemLayouter.blockSizeHoriz = new Integer(250) [package]
Definition at line 10 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.nextSystem(), and modelManagement.simulink.SystemLayouter.startWithOutports().
final Integer modelManagement.simulink.SystemLayouter.blockSizeVert = new Integer(100) [package]
Definition at line 11 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.nextSystem().
Integer modelManagement.simulink.SystemLayouter.bottom = new Integer(0) [private]
Definition at line 17 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.buildPositionString(), modelManagement.simulink.SystemLayouter.nextPort(), and modelManagement.simulink.SystemLayouter.nextSystem().
final Integer modelManagement.simulink.SystemLayouter.distanceBetweenPorts = new Integer(60) [package]
Definition at line 8 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.nextPort().
final Integer modelManagement.simulink.SystemLayouter.distanceBetweenSystmes = new Integer(90) [package]
Definition at line 9 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.nextSystem(), and modelManagement.simulink.SystemLayouter.startWithOutports().
Integer modelManagement.simulink.SystemLayouter.left = new Integer(35) [private]
Definition at line 16 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.buildPositionString(), modelManagement.simulink.SystemLayouter.nextPort(), modelManagement.simulink.SystemLayouter.nextSystem(), modelManagement.simulink.SystemLayouter.startWithOutports(), and modelManagement.simulink.SystemLayouter.startWithSystems().
final Integer modelManagement.simulink.SystemLayouter.portSizeHoriz = new Integer(30) [package]
Definition at line 12 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.nextPort().
final Integer modelManagement.simulink.SystemLayouter.portSizeVert = new Integer(14) [package]
Definition at line 13 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.nextPort().
Integer modelManagement.simulink.SystemLayouter.right = new Integer(0) [private]
Definition at line 18 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.buildPositionString(), modelManagement.simulink.SystemLayouter.nextPort(), and modelManagement.simulink.SystemLayouter.nextSystem().
Integer modelManagement.simulink.SystemLayouter.top = new Integer(40) [private]
Definition at line 15 of file SystemLayouter.java.
Referenced by modelManagement.simulink.SystemLayouter.buildPositionString(), modelManagement.simulink.SystemLayouter.nextPort(), modelManagement.simulink.SystemLayouter.nextSystem(), modelManagement.simulink.SystemLayouter.startWithOutports(), and modelManagement.simulink.SystemLayouter.startWithSystems().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/SystemLayouter.java