Carlota: modelManagement.test.SimulinkModelManagerTest Class Reference
modelManagement.test.SimulinkModelManagerTest Class Reference
Public Member Functions
SimulinkModelManager testInstanceCreation () throws InvalidURIException
SimulinkModelManager testReplacExtension (SimulinkModelManager aModelMgr)
SimulinkModelManager testExtension (SimulinkModelManager aModelMgr)
SimulinkModelManager testMetaModelRegistration (SimulinkModelManager aModelMgr)
SimulinkModelManager testLoadIt (SimulinkModelManager aModelMgr) throws InvalidModelException
EObject testGetTopElement (SimulinkModelManager aModelMgr)
void testNewModel ()
Private Attributes
String modelPath = "testWorkspace/demo.simulink"
URI model = URI.createFileURI(modelPath)
Detailed Description
Definition at line 25 of file SimulinkModelManagerTest.java.
Member Function Documentation
SimulinkModelManager modelManagement.test.SimulinkModelManagerTest.testExtension (SimulinkModelManager aModelMgr)
Definition at line 48 of file SimulinkModelManagerTest.java.
EObject modelManagement.test.SimulinkModelManagerTest.testGetTopElement (SimulinkModelManager aModelMgr)
Definition at line 86 of file SimulinkModelManagerTest.java.
SimulinkModelManager modelManagement.test.SimulinkModelManagerTest.testInstanceCreation () throws InvalidURIException
Definition at line 31 of file SimulinkModelManagerTest.java.
SimulinkModelManager modelManagement.test.SimulinkModelManagerTest.testLoadIt (SimulinkModelManager aModelMgr) throws InvalidModelException
Definition at line 71 of file SimulinkModelManagerTest.java.
References modelManagement.exceptions.InvalidModelException.dumpInvalidObjectsToConsole().
SimulinkModelManager modelManagement.test.SimulinkModelManagerTest.testMetaModelRegistration (SimulinkModelManager aModelMgr)
Definition at line 55 of file SimulinkModelManagerTest.java.
void modelManagement.test.SimulinkModelManagerTest.testNewModel ()
Definition at line 95 of file SimulinkModelManagerTest.java.
References modelManagement.simulink.SimulinkModelManager.getFactory(), modelManagement.ModelManager.getTopElement(), modelManagement.ModelManager.loadIt(), modelManagement.ModelManager.saveIt(), and modelManagement.ModelManager.setTopElement().
SimulinkModelManager modelManagement.test.SimulinkModelManagerTest.testReplacExtension (SimulinkModelManager aModelMgr)
Definition at line 40 of file SimulinkModelManagerTest.java.
References modelManagement.ModelManager.replaceExtension().
Member Data Documentation
URI modelManagement.test.SimulinkModelManagerTest.model = URI.createFileURI(modelPath) [private]
Definition at line 28 of file SimulinkModelManagerTest.java.
String modelManagement.test.SimulinkModelManagerTest.modelPath = "testWorkspace/demo.simulink" [private]
Definition at line 27 of file SimulinkModelManagerTest.java.
The documentation for this class was generated from the following file:
src/modelManagement/test/SimulinkModelManagerTest.java