Carlota: modelManagement.test.SimulinkEcoreCreatorTest Class Reference
modelManagement.test.SimulinkEcoreCreatorTest Class Reference
Public Member Functions
void testSimulinkEcoreCreator ()
Model testNewModel ()
System testRootSystem (Model aModel)
System testFindSystem (System rootSystem)
System testChild (System rootSystem)
System testReferences (System aSystem)
System testSystemContainment (System aSystem)
System testPorts (System aSystem)
System testLines (System parent)
System testFindPorts (System parent)
System testAddLines (System parent)
System testPortNotFound (System parent)
System testAddSystemWithPList (System parent)
System testFindInRepository (System parent)
Private Attributes
SimulinkModelManager modelManager
SimulinkEcoreCreator simulinkEcoreCreator
Detailed Description
Definition at line 34 of file SimulinkEcoreCreatorTest.java.
Member Function Documentation
System modelManagement.test.SimulinkEcoreCreatorTest.testAddLines (System parent)
Definition at line 151 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.addInPort(), modelManagement.simulink.SimulinkEcoreCreator.addLines(), modelManagement.simulink.SimulinkEcoreCreator.addOutPort(), modelManagement.simulink.SimulinkEcoreCreator.findSystem(), modelManagement.simulink.LineInfo.setDstPort(), modelManagement.simulink.LineInfo.setName(), and modelManagement.simulink.LineInfo.setSrcPort().
System modelManagement.test.SimulinkEcoreCreatorTest.testAddSystemWithPList (System parent)
Definition at line 220 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.addSystem(), and modelManagement.simulink.SimulinkEcoreCreator.findSystemReference().
System modelManagement.test.SimulinkEcoreCreatorTest.testChild (System rootSystem)
Definition at line 73 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.addSystem().
System modelManagement.test.SimulinkEcoreCreatorTest.testFindInRepository (System parent)
Definition at line 231 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.findLine(), modelManagement.simulink.SimulinkEcoreCreator.findPort(), and modelManagement.simulink.SimulinkEcoreCreator.findSystem().
System modelManagement.test.SimulinkEcoreCreatorTest.testFindPorts (System parent)
Definition at line 133 of file SimulinkEcoreCreatorTest.java.
System modelManagement.test.SimulinkEcoreCreatorTest.testFindSystem (System rootSystem)
Definition at line 65 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.findSystem().
System modelManagement.test.SimulinkEcoreCreatorTest.testLines (System parent)
Definition at line 118 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.addInPort(), modelManagement.simulink.SimulinkEcoreCreator.addLine(), modelManagement.simulink.SimulinkEcoreCreator.addOutPort(), and modelManagement.simulink.SimulinkEcoreCreator.addSystem().
Model modelManagement.test.SimulinkEcoreCreatorTest.testNewModel ()
Definition at line 49 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.getTopElement(), and modelManagement.simulink.SimulinkEcoreCreator.newModel().
System modelManagement.test.SimulinkEcoreCreatorTest.testPortNotFound (System parent)
Definition at line 193 of file SimulinkEcoreCreatorTest.java.
System modelManagement.test.SimulinkEcoreCreatorTest.testPorts (System aSystem)
Definition at line 103 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.addInPort(), and modelManagement.simulink.SimulinkEcoreCreator.addOutPort().
System modelManagement.test.SimulinkEcoreCreatorTest.testReferences (System aSystem)
Definition at line 82 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.addSystem(), and modelManagement.simulink.SimulinkEcoreCreator.findSystem().
System modelManagement.test.SimulinkEcoreCreatorTest.testRootSystem (Model aModel)
Definition at line 57 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.addRootSystem().
void modelManagement.test.SimulinkEcoreCreatorTest.testSimulinkEcoreCreator ()
Definition at line 40 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkModelManager.getFactory().
System modelManagement.test.SimulinkEcoreCreatorTest.testSystemContainment (System aSystem)
Definition at line 92 of file SimulinkEcoreCreatorTest.java.
References modelManagement.simulink.SimulinkEcoreCreator.addSystem(), and modelManagement.simulink.SimulinkEcoreCreator.getTopElement().
Member Data Documentation
SimulinkModelManager modelManagement.test.SimulinkEcoreCreatorTest.modelManager [private]
Definition at line 36 of file SimulinkEcoreCreatorTest.java.
SimulinkEcoreCreator modelManagement.test.SimulinkEcoreCreatorTest.simulinkEcoreCreator [private]
Definition at line 37 of file SimulinkEcoreCreatorTest.java.
The documentation for this class was generated from the following file:
src/modelManagement/test/SimulinkEcoreCreatorTest.java