Carlota: modelManagement.simulink.LinesProcessor Class Reference
modelManagement.simulink.LinesProcessor Class Reference
Static Public Member Functions
static Collection<?extends
ProtoObject > doIt (System aSystem)
Package Attributes
System theSystem
Private Member Functions
Collection<?extends ProtoObject > process ()
void process (Line aLine)
String processPort (Line aLine, Port port)
Integer findPosInBlock (System aSystem, Port port)
System obtainPortParent (Port port)
SystemReference findBlockNameWithinReferences (Line aLine, System portParentSys)
boolean portBelongsToSubsystem (Line aLine, System portParentSys)
Detailed Description
Definition at line 14 of file LinesProcessor.java.
Member Function Documentation
static Collection<? extends ProtoObject> modelManagement.simulink.LinesProcessor.doIt (System aSystem) [static]
Definition at line 18 of file LinesProcessor.java.
References modelManagement.simulink.LinesProcessor.process(), and modelManagement.simulink.LinesProcessor.theSystem.
SystemReference modelManagement.simulink.LinesProcessor.findBlockNameWithinReferences (Line aLine, System portParentSys) [private]
Definition at line 78 of file LinesProcessor.java.
Referenced by modelManagement.simulink.LinesProcessor.processPort().
Integer modelManagement.simulink.LinesProcessor.findPosInBlock (System aSystem, Port port) [private]
Definition at line 55 of file LinesProcessor.java.
Referenced by modelManagement.simulink.LinesProcessor.processPort().
System modelManagement.simulink.LinesProcessor.obtainPortParent (Port port) [private]
Definition at line 63 of file LinesProcessor.java.
Referenced by modelManagement.simulink.LinesProcessor.processPort().
boolean modelManagement.simulink.LinesProcessor.portBelongsToSubsystem (Line aLine, System portParentSys) [private]
Definition at line 87 of file LinesProcessor.java.
Referenced by modelManagement.simulink.LinesProcessor.processPort().
void modelManagement.simulink.LinesProcessor.process (Line aLine) [private]
Definition at line 34 of file LinesProcessor.java.
References modelManagement.simulink.LinesProcessor.processPort().
Collection<? extends ProtoObject> modelManagement.simulink.LinesProcessor.process () [private]
Definition at line 25 of file LinesProcessor.java.
References modelManagement.simulink.LinesProcessor.theSystem.
Referenced by modelManagement.simulink.LinesProcessor.doIt().
String modelManagement.simulink.LinesProcessor.processPort (Line aLine, Port port) [private]
Definition at line 43 of file LinesProcessor.java.
References modelManagement.simulink.LinesProcessor.findBlockNameWithinReferences(), modelManagement.simulink.LinesProcessor.findPosInBlock(), modelManagement.simulink.LinesProcessor.obtainPortParent(), and modelManagement.simulink.LinesProcessor.portBelongsToSubsystem().
Referenced by modelManagement.simulink.LinesProcessor.process().
Member Data Documentation
System modelManagement.simulink.LinesProcessor.theSystem [package]
Definition at line 16 of file LinesProcessor.java.
Referenced by modelManagement.simulink.LinesProcessor.doIt(), and modelManagement.simulink.LinesProcessor.process().
The documentation for this class was generated from the following file:
src/modelManagement/simulink/LinesProcessor.java